"""
Django settings for trabajofinal project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Cargar variables de entorno desde .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key-for-development')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# ✅ CONFIGURACIÓN PARA DESARROLLO LOCAL
ALLOWED_HOSTS = [
    '127.0.0.1', 
    'localhost', 
    '127.0.0.1:8000', 
    'localhost:8000',
    'uncategorized-noncommodiously-floy.ngrok-free.dev',
    '*.ngrok-free.dev',
]

# ✅ CONFIGURACIÓN CSRF PARA EVITAR ERRORES 403
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'https://127.0.0.1:8000',
    'https://localhost:8000',
    'https://uncategorized-noncommodiously-floy.ngrok-free.dev',
    'https://*.ngrok-free.dev',
]

# Si tu app está detrás de un proxy/terminador TLS (ej: ngrok),
# habilita esta cabecera para que Django detecte esquema https correctamente.
# Esto ayuda a que social-auth y Django construyan `https://` en URLs absolutas.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ✅ CONFIGURACIONES ADICIONALES CSRF PARA ADMIN
CSRF_COOKIE_SECURE = False  # Para desarrollo HTTP (no HTTPS)
CSRF_COOKIE_HTTPONLY = False  # Permitir acceso por JavaScript si es necesario
CSRF_USE_SESSIONS = False  # Usar cookies en lugar de sesiones
CSRF_COOKIE_SAMESITE = 'Lax'  # Política de SameSite relajada para desarrollo

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #app local (puse yo mi app llamada accounts)
    'accounts',
    'cine', #agregado por mi maneja el cine
    'ventas', #agregado por mi maneja las ventas
    'core', # ✅ App core para notificaciones y servicios compartidos
    'promociones',
    'social_django', #  esta línea para la autenticación social
    'widget_tweaks', #  esta línea para personalizar widgets en templates

    'simple_history', # esta línea para el historial de cambios en modelos
    # App para mostrar auditoría consolidada en Admin
    'auditoria.apps.AuditoriaConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # ✅ AÑADIR ESTA LÍNEA PARA OAUTH
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'trabajofinal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                # ✅ AÑADIR ESTAS LÍNEAS PARA OAUTH
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                
                # ✅ Context processor para configuración del cine
                'cine.context_processors.configuracion_cine',
            ],
        },
    },
]

WSGI_APPLICATION = 'trabajofinal.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'cinegest'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'

# ✅ ARCHIVOS ESTÁTICOS PARA DESARROLLO
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# ✅ ARCHIVOS ESTÁTICOS PARA PRODUCCIÓN (collectstatic)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de usuario personalizado y autenticación
AUTH_USER_MODEL = 'accounts.Usuario'  # modelo personalizado
LOGIN_URL = '/accounts/login/'     # URL a la que redirigir si no está logueado
LOGIN_REDIRECT_URL = '/accounts/dashboard/'  # a dónde ir tras login
LOGOUT_REDIRECT_URL = '/accounts/login/'     # tras logout

# gestiona imagenes
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ✅ ✅ ✅ CONFIGURACIÓN COMPLETA DE OAUTH2 - ESTO ES LO QUE FALTABA ✅ ✅ ✅

# Backends de autenticación
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',  # Backend para Google OAuth2
    'django.contrib.auth.backends.ModelBackend',  # Backend tradicional de Django
)

# Google OAuth2 Configuration (from .env file)
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('GOOGLE_CLIENT_ID', '')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')

# Permisos que solicitamos a Google
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',    # Email del usuario
    'https://www.googleapis.com/auth/userinfo.profile',  # Información básica del perfil
]

# URLs de redirección después del login/logout
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/accounts/dashboard/'  # Después del login exitoso
SOCIAL_AUTH_LOGIN_ERROR_URL = '/accounts/login/?error=oauth'  # Si hay error
SOCIAL_AUTH_LOGOUT_REDIRECT_URL = '/accounts/login/'  # Después del logout

# Configuración adicional de Google OAuth2
SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
    'access_type': 'offline',  # Obtener refresh tokens
    'approval_prompt': 'auto'  # Solo pedir permisos la primera vez
}

# ✅ CONFIGURACIÓN PARA MANEJAR USUARIOS EXISTENTES
SOCIAL_AUTH_USER_MODEL = 'accounts.Usuario'  # Usar nuestro modelo personalizado

# ✅ Pipeline PERSONALIZADO que maneja usuarios existentes correctamente
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',    # Obtiene detalles del usuario
    'social_core.pipeline.social_auth.social_uid',        # Obtiene ID único de Google
    'social_core.pipeline.social_auth.auth_allowed',      # Verifica si puede autenticarse
    'accounts.pipeline.custom_social_user',               # Busca asociación social existente
    'social_core.pipeline.user.get_username',             # Genera username único
    'accounts.pipeline.associate_by_email',               # Asocia por email si existe usuario
    'social_core.pipeline.user.create_user',              # Crea usuario si no existe
    'social_core.pipeline.social_auth.associate_user',    # CRÍTICO: Crea la asociación UserSocialAuth
    'accounts.pipeline.setup_user_profile',               # Función personalizada para perfil
    'social_core.pipeline.social_auth.load_extra_data',   # Carga datos extra
    'social_core.pipeline.user.user_details',             # Actualiza detalles del usuario
)

# Configuración de sesiones para OAuth
SOCIAL_AUTH_SESSION_EXPIRATION = False  # Las sesiones no expiran automáticamente

# ✅ CONFIGURACIÓN ADICIONAL PARA DEBUG Y SEGURIDAD
SOCIAL_AUTH_RAISE_EXCEPTIONS = False   # No lanzar excepciones, redirigir en caso de error
# Forzar que los redirect_uris construidos por social-auth sean HTTPS
# Útil en desarrollo cuando expones el servidor con ngrok / proxy TLS.
SOCIAL_AUTH_REDIRECT_IS_HTTPS = os.getenv('SOCIAL_AUTH_REDIRECT_IS_HTTPS', 'True') == 'True' #este sirve por si falla ngrok
SOCIAL_AUTH_URL_NAMESPACE = 'social'   # Namespace para las URLs

# Configuración adicional que puede ayudar con errores 403
SOCIAL_AUTH_SANITIZE_REDIRECTS = False
SOCIAL_AUTH_LOGIN_ERROR_URL = '/accounts/login/?error=oauth'

# ✅ CONFIGURACIÓN ESPECÍFICA PARA DESARROLLO LOCAL (Ya definida arriba)

# ✅ LOGGING PARA VER ERRORES OAUTH EN DETALLE
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'social_core': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'social_django': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# ============================================
# EMAIL CONFIGURATION
# ============================================
# MailCrab para desarrollo (servidor SMTP de prueba)
# Ver: https://tweedegolf.nl/en/blog/104/mailcrab-an-email-test-server-for-development
if DEBUG:
    # MailCrab corre en localhost:1025 por defecto
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '1025'))
    EMAIL_USE_TLS = False
    EMAIL_USE_SSL = False
    EMAIL_HOST_USER = ''
    EMAIL_HOST_PASSWORD = ''
    DEFAULT_FROM_EMAIL = 'CineGest <noreply@cinegest.local>'
else:
    # Configuración para producción (ejemplo con Gmail/SendGrid/etc)
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@cinegest.com')

# ============================================
# MERCADO PAGO CONFIGURATION
# ============================================
# Credenciales de prueba de Mercado Pago (TEST)
# Para producción, configura las variables de entorno
MERCADOPAGO_ACCESS_TOKEN = os.getenv('MERCADOPAGO_ACCESS_TOKEN')
MERCADOPAGO_PUBLIC_KEY = os.getenv('MERCADOPAGO_PUBLIC_KEY')

