# Generated by Django 5.2.6 on 2025-11-12 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True)),
                ('history_type', models.CharField(max_length=1)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, null=True)),
                ('history_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de Auditoría',
                'verbose_name_plural': 'Entradas de Auditoría',
                'ordering': ['-history_date'],
            },
        ),
    ]
