# Generated by Django 5.2.6 on 2025-11-13 00:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditentry',
            options={'ordering': ['-history_date', '-created_at'], 'verbose_name': 'Entrada de Auditoría', 'verbose_name_plural': 'Entradas de Auditoría'},
        ),
        migrations.AddField(
            model_name='auditentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha de creación de esta entrada de auditoría'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='history_change_reason',
            field=models.TextField(blank=True, help_text='Razón del cambio (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='history_date',
            field=models.DateTimeField(db_index=True, help_text='Fecha y hora del cambio'),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='history_type',
            field=models.CharField(choices=[('+', 'Creación'), ('~', 'Actualización'), ('-', 'Eliminación')], db_index=True, help_text='Tipo de operación realizada', max_length=1),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='history_user',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='model_name',
            field=models.CharField(db_index=True, help_text='Nombre de la tabla del modelo', max_length=200),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID del objeto auditado', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='object_repr',
            field=models.CharField(blank=True, help_text='Representación en texto del objeto', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot completo del objeto en ese momento', null=True),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['-history_date', 'model_name'], name='auditoria_a_history_e14ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['model_name', 'object_id'], name='auditoria_a_model_n_c70525_idx'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['history_user', '-history_date'], name='auditoria_a_history_6f2171_idx'),
        ),
    ]
