# Generated by Django 5.2.6 on 2025-12-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_alter_auditentry_options_auditentry_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_days', models.PositiveIntegerField(default=90, help_text='Días que se conservan los registros de auditoría antes de ser eliminados automáticamente', verbose_name='Días de Retención')),
                ('auto_cleanup_enabled', models.BooleanField(default=False, help_text='Si está activado, los registros antiguos se eliminan automáticamente según retention_days', verbose_name='Limpieza Automática Habilitada')),
                ('excluded_models', models.TextField(blank=True, default='', help_text='Nombres de modelos separados por comas para excluir de AuditEntry (ej: venta,entrada)', verbose_name='Modelos Excluidos')),
                ('last_cleanup', models.DateTimeField(blank=True, help_text='Fecha y hora de la última limpieza automática', null=True, verbose_name='Última Limpieza')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Auditoría',
                'verbose_name_plural': 'Configuración de Auditoría',
            },
        ),
    ]
