# Generated by Django 5.2.6 on 2025-11-06 00:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_empleado_cargo'),
        ('cine', '0012_formato_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'Metodo_pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Compra')),
                ('tipo_venta', models.CharField(choices=[('ONLINE', 'Online'), ('PRESENCIAL', 'Presencial')], default='ONLINE', max_length=20, verbose_name='Tipo de Venta')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PENDIENTE_PAGO', 'Pendiente de Pago'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='accounts.cliente', verbose_name='Cliente')),
                ('id_empleado', models.ForeignKey(blank=True, help_text='Empleado que procesó la venta (solo para ventas presenciales)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_procesadas', to='accounts.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'Venta',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id_reembolso', models.AutoField(primary_key=True, serialize=False)),
                ('monto_reembolso', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Reembolso')),
                ('fecha_reembolso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Reembolso')),
                ('motivo', models.TextField(blank=True, help_text='Razón del reembolso', verbose_name='Motivo')),
                ('id_pelicula', models.ForeignKey(help_text='Película relacionada con el reembolso', on_delete=django.db.models.deletion.PROTECT, related_name='reembolsos', to='cine.pelicula', verbose_name='Película')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
                'db_table': 'Reembolso',
                'ordering': ['-fecha_reembolso'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('nro_transaccion', models.CharField(blank=True, help_text='ID de transacción de Mercado Pago u otro procesador', max_length=100, null=True, verbose_name='Número de Transacción')),
                ('id_metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='ventas.metodopago', verbose_name='Método de Pago')),
                ('id_venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pago',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('RESERVADA', 'Reservada'), ('VENDIDA', 'Vendida'), ('USADA', 'Usada'), ('CANCELADA', 'Cancelada')], default='RESERVADA', max_length=20, verbose_name='Estado')),
                ('id_butaca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='cine.butaca', verbose_name='Butaca')),
                ('id_funcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='cine.funcion', verbose_name='Función')),
                ('id_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='cine.pelicula', verbose_name='Película')),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='cine.sala', verbose_name='Sala')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'db_table': 'Entrada',
                'ordering': ['id_funcion', 'id_butaca'],
                'unique_together': {('id_funcion', 'id_butaca')},
            },
        ),
    ]
