# Generated by Django 5.2.6 on 2025-11-12 21:38

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_historicalusuario'),
        ('cine', '0016_historicalfuncion_historicalpelicula_historicalsala'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEntrada',
            fields=[
                ('id_entrada', models.IntegerField(blank=True, db_index=True)),
                ('estado', models.CharField(choices=[('RESERVADA', 'Reservada'), ('VENDIDA', 'Vendida'), ('USADA', 'Usada'), ('CANCELADA', 'Cancelada')], default='RESERVADA', max_length=20, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_butaca', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cine.butaca', verbose_name='Butaca')),
                ('id_funcion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cine.funcion', verbose_name='Función')),
                ('id_pelicula', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cine.pelicula', verbose_name='Película')),
                ('id_sala', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cine.sala', verbose_name='Sala')),
                ('id_venta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'historical Entrada',
                'verbose_name_plural': 'historical Entradas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVenta',
            fields=[
                ('id_venta', models.IntegerField(blank=True, db_index=True)),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Compra')),
                ('tipo_venta', models.CharField(choices=[('ONLINE', 'Online'), ('PRESENCIAL', 'Presencial')], default='ONLINE', max_length=20, verbose_name='Tipo de Venta')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PENDIENTE_PAGO', 'Pendiente de Pago'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.cliente', verbose_name='Cliente')),
                ('id_empleado', models.ForeignKey(blank=True, db_constraint=False, help_text='Empleado que procesó la venta (solo para ventas presenciales)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'historical Venta',
                'verbose_name_plural': 'historical Ventas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
