# Generated by Django 5.2.6 on 2025-11-14 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_historicalentrada_historicalventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaReembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_minimas_antes_evento', models.PositiveIntegerField(unique=True, verbose_name='Horas Mínimas Antes del Evento')),
                ('porcentaje_reembolso', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje a Reembolsar (%)')),
            ],
            options={
                'verbose_name': 'Política de Reembolso',
                'verbose_name_plural': 'Políticas de Reembolso',
                'ordering': ['-horas_minimas_antes_evento'],
            },
        ),
    ]
