# Generated by Django 5.2.6 on 2025-11-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_politicareembolso'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicareembolso',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si esta política está habilitada', verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='nombre',
            field=models.CharField(default='Política existente', help_text='Nombre identificador de la política (ej. "Corta antelación").', max_length=150, verbose_name='Nombre de la Política'),
            preserve_default=False,
        ),
    ]
