# Generated by Django 5.2.6 on 2025-11-19 15:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0016_historicalfuncion_historicalpelicula_historicalsala'),
        ('ventas', '0006_remove_reembolso_table'),
    ]

    operations = [
        # Paso 1: Usar SQL puro para agregar columnas solo si NO existen
        migrations.RunSQL(
            sql="""
                -- Agregar columnas solo si no existen
                DO $$ 
                BEGIN
                    -- activo
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_schema='public' 
                        AND table_name='ventas_politicareembolso' 
                        AND column_name='activo'
                    ) THEN
                        ALTER TABLE ventas_politicareembolso ADD COLUMN activo BOOLEAN DEFAULT TRUE NOT NULL;
                    END IF;
                    
                    -- created_at
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_schema='public' 
                        AND table_name='ventas_politicareembolso' 
                        AND column_name='created_at'
                    ) THEN
                        ALTER TABLE ventas_politicareembolso ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL;
                    END IF;
                    
                    -- dias_antes_minimo
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_schema='public' 
                        AND table_name='ventas_politicareembolso' 
                        AND column_name='dias_antes_minimo'
                    ) THEN
                        ALTER TABLE ventas_politicareembolso ADD COLUMN dias_antes_minimo INTEGER DEFAULT 1 NOT NULL;
                    END IF;
                    
                    -- max_cambios_por_compra
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_schema='public' 
                        AND table_name='ventas_politicareembolso' 
                        AND column_name='max_cambios_por_compra'
                    ) THEN
                        ALTER TABLE ventas_politicareembolso ADD COLUMN max_cambios_por_compra INTEGER DEFAULT 1 NOT NULL;
                    END IF;
                    
                    -- penalidad_percent
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_schema='public' 
                        AND table_name='ventas_politicareembolso' 
                        AND column_name='penalidad_percent'
                    ) THEN
                        ALTER TABLE ventas_politicareembolso ADD COLUMN penalidad_percent NUMERIC(5,2) DEFAULT 0.00 NOT NULL;
                    END IF;
                    
                    -- permitir_intercambio
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_schema='public' 
                        AND table_name='ventas_politicareembolso' 
                        AND column_name='permitir_intercambio'
                    ) THEN
                        ALTER TABLE ventas_politicareembolso ADD COLUMN permitir_intercambio BOOLEAN DEFAULT TRUE NOT NULL;
                    END IF;
                    
                    -- updated_at
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_schema='public' 
                        AND table_name='ventas_politicareembolso' 
                        AND column_name='updated_at'
                    ) THEN
                        ALTER TABLE ventas_politicareembolso ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL;
                    END IF;
                END $$;
                
                -- Eliminar columnas antiguas solo si existen
                DO $$ 
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_schema='public' 
                        AND table_name='ventas_politicareembolso' 
                        AND column_name='horas_minimas_antes_evento'
                    ) THEN
                        ALTER TABLE ventas_politicareembolso DROP COLUMN horas_minimas_antes_evento;
                    END IF;
                    
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_schema='public' 
                        AND table_name='ventas_politicareembolso' 
                        AND column_name='is_active'
                    ) THEN
                        ALTER TABLE ventas_politicareembolso DROP COLUMN is_active;
                    END IF;
                    
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_schema='public' 
                        AND table_name='ventas_politicareembolso' 
                        AND column_name='porcentaje_reembolso'
                    ) THEN
                        ALTER TABLE ventas_politicareembolso DROP COLUMN porcentaje_reembolso;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        
        # Paso 2: Crear el modelo Intercambio (tabla nueva)
        migrations.CreateModel(
            name='Intercambio',
            fields=[
                ('id_intercambio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_intercambio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Intercambio')),
                ('motivo', models.CharField(choices=[('HORARIO', 'Cambio de horario'), ('FECHA', 'Cambio de fecha'), ('PELICULA', 'Cambio de película'), ('DISPONIBILIDAD', 'Disponibilidad de asientos'), ('OTRO', 'Otro motivo')], default='OTRO', max_length=20, verbose_name='Motivo del Intercambio')),
                ('estado', models.CharField(choices=[('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido'), ('REVERTIDO', 'Revertido')], default='COMPLETADO', max_length=20, verbose_name='Estado')),
                ('cantidad_entradas', models.IntegerField(help_text='Número de entradas que se intercambiaron', verbose_name='Cantidad de Entradas Intercambiadas')),
                ('penalidad_aplicada', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto de penalidad cobrado (si aplica)', max_digits=10, verbose_name='Penalidad Aplicada')),
                ('notas', models.TextField(blank=True, help_text='Información adicional sobre el intercambio', null=True, verbose_name='Notas')),
                ('usuario_email', models.EmailField(help_text='Email del cliente que realizó el intercambio', max_length=254, verbose_name='Email del Usuario')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('funcion_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intercambios_destino', to='cine.funcion', verbose_name='Nueva Función')),
                ('funcion_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intercambios_origen', to='cine.funcion', verbose_name='Función Original')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intercambios', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Intercambio de Entrada',
                'verbose_name_plural': 'Intercambios de Entradas',
                'db_table': 'ventas_intercambio',
                'ordering': ['-fecha_intercambio'],
            },
        ),
        
        # Paso 3: Agregar índices
        migrations.AddIndex(
            model_name='intercambio',
            index=models.Index(fields=['venta', 'fecha_intercambio'], name='ventas_inte_venta_i_8b6b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='intercambio',
            index=models.Index(fields=['estado'], name='ventas_inte_estado_7e8c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='intercambio',
            index=models.Index(fields=['funcion_origen'], name='ventas_inte_funcion_6e5d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='intercambio',
            index=models.Index(fields=['funcion_destino'], name='ventas_inte_funcion_3f2a1b_idx'),
        ),
    ]
