# Generated by Django 5.2.6 on 2025-11-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_safe_intercambio_migration'),
    ]

    operations = [
    ]
