# Generated by Django 5.2.6 on 2025-11-20 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_auto_20251119_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reembolso',
            name='id_pelicula',
        ),
        migrations.RemoveField(
            model_name='reembolso',
            name='id_venta',
        ),
        migrations.AlterModelOptions(
            name='politicareembolso',
            options={'verbose_name': 'Política de Reembolso/Intercambio', 'verbose_name_plural': 'Políticas de Reembolso/Intercambio'},
        ),
        migrations.RenameIndex(
            model_name='intercambio',
            new_name='ventas_inte_venta_i_a3e51e_idx',
            old_name='ventas_inte_venta_i_8b6b5e_idx',
        ),
        migrations.RenameIndex(
            model_name='intercambio',
            new_name='ventas_inte_estado_f7fc6c_idx',
            old_name='ventas_inte_estado_7e8c6f_idx',
        ),
        migrations.RenameIndex(
            model_name='intercambio',
            new_name='ventas_inte_funcion_b26f17_idx',
            old_name='ventas_inte_funcion_6e5d4a_idx',
        ),
        migrations.RenameIndex(
            model_name='intercambio',
            new_name='ventas_inte_funcion_75aeec_idx',
            old_name='ventas_inte_funcion_3f2a1b_idx',
        ),
        migrations.RunSQL(
            sql=("ALTER TABLE IF EXISTS \"ventas_politicareembolso\" DROP COLUMN IF EXISTS \"horas_minimas_antes_evento\" CASCADE;"),
            reverse_sql=("-- Reverse of dropping horas_minimas_antes_evento: no-op.\n"),
        ),
        migrations.RunSQL(
            sql=("ALTER TABLE IF EXISTS \"ventas_politicareembolso\" DROP COLUMN IF EXISTS \"is_active\" CASCADE;"),
            reverse_sql=("-- Reverse of dropping is_active: no-op.\n"),
        ),
        migrations.RunSQL(
            sql=("ALTER TABLE IF EXISTS \"ventas_politicareembolso\" DROP COLUMN IF EXISTS \"porcentaje_reembolso\" CASCADE;"),
            reverse_sql=("-- Reverse of dropping porcentaje_reembolso: no-op.\n"),
        ),
        migrations.RunSQL(
            sql=("ALTER TABLE IF EXISTS \"ventas_politicareembolso\" ADD COLUMN IF NOT EXISTS \"activo\" BOOLEAN DEFAULT TRUE NOT NULL;"),
            reverse_sql=("-- reverse no-op for activo\n"),
        ),
        migrations.RunSQL(
            sql=("ALTER TABLE IF EXISTS \"ventas_politicareembolso\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL;"),
            reverse_sql=("-- reverse no-op for created_at\n"),
        ),
        migrations.RunSQL(
            sql=("ALTER TABLE IF EXISTS \"ventas_politicareembolso\" ADD COLUMN IF NOT EXISTS \"dias_antes_minimo\" INTEGER DEFAULT 1 NOT NULL;"),
            reverse_sql=("-- reverse no-op for dias_antes_minimo\n"),
        ),
        migrations.RunSQL(
            sql=("ALTER TABLE IF EXISTS \"ventas_politicareembolso\" ADD COLUMN IF NOT EXISTS \"max_cambios_por_compra\" INTEGER DEFAULT 1 NOT NULL;"),
            reverse_sql=("-- reverse no-op for max_cambios_por_compra\n"),
        ),
        migrations.RunSQL(
            sql=("ALTER TABLE IF EXISTS \"ventas_politicareembolso\" ADD COLUMN IF NOT EXISTS \"penalidad_percent\" NUMERIC(5,2) DEFAULT 0.00 NOT NULL;"),
            reverse_sql=("-- reverse no-op for penalidad_percent\n"),
        ),
        migrations.RunSQL(
            sql=("ALTER TABLE IF EXISTS \"ventas_politicareembolso\" ADD COLUMN IF NOT EXISTS \"permitir_intercambio\" BOOLEAN DEFAULT TRUE NOT NULL;"),
            reverse_sql=("-- reverse no-op for permitir_intercambio\n"),
        ),
        migrations.RunSQL(
            sql=("ALTER TABLE IF EXISTS \"ventas_politicareembolso\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL;"),
            reverse_sql=("-- reverse no-op for updated_at\n"),
        ),
        migrations.AlterField(
            model_name='politicareembolso',
            name='nombre',
            field=models.CharField(default='Política de Intercambio', max_length=140),
        ),
        migrations.DeleteModel(
            name='Reembolso',
        ),
    ]
