# Generated by Django 5.2.6 on 2025-11-20 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_auto_20251119_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reembolso',
            name='id_pelicula',
        ),
        migrations.RemoveField(
            model_name='reembolso',
            name='id_venta',
        ),
        migrations.AlterModelOptions(
            name='politicareembolso',
            options={'verbose_name': 'Política de Reembolso/Intercambio', 'verbose_name_plural': 'Políticas de Reembolso/Intercambio'},
        ),
        migrations.RenameIndex(
            model_name='intercambio',
            new_name='ventas_inte_venta_i_a3e51e_idx',
            old_name='ventas_inte_venta_i_8b6b5e_idx',
        ),
        migrations.RenameIndex(
            model_name='intercambio',
            new_name='ventas_inte_estado_f7fc6c_idx',
            old_name='ventas_inte_estado_7e8c6f_idx',
        ),
        migrations.RenameIndex(
            model_name='intercambio',
            new_name='ventas_inte_funcion_b26f17_idx',
            old_name='ventas_inte_funcion_6e5d4a_idx',
        ),
        migrations.RenameIndex(
            model_name='intercambio',
            new_name='ventas_inte_funcion_75aeec_idx',
            old_name='ventas_inte_funcion_3f2a1b_idx',
        ),
        migrations.RemoveField(
            model_name='politicareembolso',
            name='horas_minimas_antes_evento',
        ),
        migrations.RemoveField(
            model_name='politicareembolso',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='politicareembolso',
            name='porcentaje_reembolso',
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='dias_antes_minimo',
            field=models.IntegerField(default=1, help_text='Número mínimo de días antes de la función para permitir intercambio'),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='max_cambios_por_compra',
            field=models.IntegerField(default=1, help_text='Máximo de intercambios permitidos por compra (0 = ilimitado)'),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='penalidad_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de penalidad aplicado al intercambio (si aplica)', max_digits=5),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='permitir_intercambio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='politicareembolso',
            name='nombre',
            field=models.CharField(default='Política de Intercambio', max_length=140),
        ),
        migrations.DeleteModel(
            name='Reembolso',
        ),
    ]
