# Generated by Django 5.2.6 on 2025-11-22 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_remove_reembolso_id_pelicula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalentrada',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrada',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESERVADA', 'Reservada'), ('VENDIDA', 'Vendida'), ('USADA', 'Usada'), ('CANCELADA', 'Cancelada')], default='RESERVADA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalentrada',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESERVADA', 'Reservada'), ('VENDIDA', 'Vendida'), ('USADA', 'Usada'), ('CANCELADA', 'Cancelada')], default='RESERVADA', max_length=20, verbose_name='Estado'),
        ),
    ]
