# Generated by ChatGPT - add cupon_utilizado FK to Venta
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_entrada_reservado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cupon_utilizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_usadas', to='promociones.cupongenerado', verbose_name='Cupón Utilizado', help_text='Referencias al cupón usado para esta venta (si aplica)'),
        ),
    ]
