# Generated by Django 5.2.6 on 2025-11-29 16:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0015_yield_management'),
        ('ventas', '0026_historicalventa_medio_pago'),
    ]

    operations = [
        # Agregar codigo_compra a Venta
        migrations.AddField(
            model_name='venta',
            name='codigo_compra',
            field=models.CharField(blank=True, help_text='Código único para canje de entradas (generado automáticamente)', max_length=20, null=True, unique=True, verbose_name='Código de Compra'),
        ),
        # Agregar codigo_compra a HistoricalVenta
        migrations.AddField(
            model_name='historicalventa',
            name='codigo_compra',
            field=models.CharField(blank=True, db_index=True, help_text='Código único para canje de entradas (generado automáticamente)', max_length=20, null=True, verbose_name='Código de Compra'),
        ),
        # Agregar estado ENTREGADA a Entrada
        migrations.AlterField(
            model_name='entrada',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESERVADA', 'Reservada'), ('VENDIDA', 'Vendida'), ('ENTREGADA', 'Entregada'), ('USADA', 'Usada'), ('CANCELADA', 'Cancelada')], default='RESERVADA', max_length=20, verbose_name='Estado'),
        ),
        # Agregar estado ENTREGADA a HistoricalEntrada
        migrations.AlterField(
            model_name='historicalentrada',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESERVADA', 'Reservada'), ('VENDIDA', 'Vendida'), ('ENTREGADA', 'Entregada'), ('USADA', 'Usada'), ('CANCELADA', 'Cancelada')], default='RESERVADA', max_length=20, verbose_name='Estado'),
        ),
    ]
