# Generated by Django 5.2.6 on 2025-12-01 15:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0016_remove_vip_tipo'),
        ('ventas', '0027_agregar_codigo_compra_y_estado_entregada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicareembolso',
            name='horas_minimas_antes_evento',
        ),
        migrations.RemoveField(
            model_name='politicareembolso',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='politicareembolso',
            name='porcentaje_reembolso',
        ),
        migrations.AddField(
            model_name='historicalventa',
            name='cupon_utilizado',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Referencias al cupón usado para esta venta (si aplica)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='promociones.cupongenerado', verbose_name='Cupón Utilizado'),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='dias_antes_minimo',
            field=models.IntegerField(default=1, help_text='Número mínimo de días antes de la función para permitir intercambio'),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='max_cambios_por_compra',
            field=models.IntegerField(default=1, help_text='Máximo de intercambios permitidos por compra (0 = ilimitado)'),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='penalidad_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de penalidad aplicado al intercambio (si aplica)', max_digits=5),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='permitir_intercambio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
