# Generated by Django 5.2.6 on 2025-12-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0028_remove_vip_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalventa',
            name='codigo_compra',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Código único para canje de entradas (generado automáticamente)', max_length=20, verbose_name='Código de Compra'),
        ),
        migrations.AlterField(
            model_name='historicalventa',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('MERCADOPAGO', 'Mercado Pago'), ('TARJETA', 'Tarjeta')], default='', help_text='Medio de pago utilizado para la venta', max_length=20, verbose_name='Medio de Pago'),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='notas',
            field=models.TextField(blank=True, default='', help_text='Información adicional sobre el intercambio', verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='user_agent',
            field=models.TextField(blank=True, default='', verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='nro_transaccion',
            field=models.CharField(blank=True, default='', help_text='ID de transacción de Mercado Pago u otro procesador', max_length=100, verbose_name='Número de Transacción'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='codigo_compra',
            field=models.CharField(blank=True, default='', help_text='Código único para canje de entradas (generado automáticamente)', max_length=20, unique=True, verbose_name='Código de Compra'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('MERCADOPAGO', 'Mercado Pago'), ('TARJETA', 'Tarjeta')], default='', help_text='Medio de pago utilizado para la venta', max_length=20, verbose_name='Medio de Pago'),
        ),
    ]
