# Generated by Django 5.2.6 on 2025-12-01 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_cliente_direccion_cliente_acepta_marketing'),
        ('cine', '0028_rename_cine_butaca_sala_id_1c63a7_idx_idx_butaca_sala_fila_numero_and_more'),
        ('promociones', '0018_alter_funcionpromocion_unique_together_and_more'),
        ('ventas', '0029_alter_historicalventa_codigo_compra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Eliminados RenameIndex porque los índices originales no existen
        # Los índices se crearán al final con AddIndex
        migrations.AlterUniqueTogether(
            name='entrada',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='historicalventa',
            name='codigo_compra',
            field=models.CharField(blank=True, default='', help_text='Código único para canje de entradas (generado automáticamente)', max_length=20, verbose_name='Código de Compra'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='codigo_compra',
            field=models.CharField(blank=True, default='', help_text='Código único para canje de entradas (generado automáticamente)', max_length=20, verbose_name='Código de Compra'),
        ),
        migrations.AddConstraint(
            model_name='entrada',
            constraint=models.UniqueConstraint(fields=('id_funcion', 'id_butaca'), name='UQ_entrada_funcion_butaca'),
        ),
        migrations.AddConstraint(
            model_name='metodopago',
            constraint=models.UniqueConstraint(fields=('nombre',), name='UQ_metodo_pago_nombre'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(fields=('codigo_compra',), name='UQ_venta_codigo_compra'),
        ),
        # Agregar los índices con nombres explícitos
        migrations.AddIndex(
            model_name='intercambio',
            index=models.Index(fields=['venta', 'fecha_intercambio'], name='IDX_int_venta_fecha'),
        ),
        migrations.AddIndex(
            model_name='intercambio',
            index=models.Index(fields=['estado'], name='IDX_int_estado'),
        ),
        migrations.AddIndex(
            model_name='intercambio',
            index=models.Index(fields=['funcion_origen'], name='IDX_int_func_origen'),
        ),
        migrations.AddIndex(
            model_name='intercambio',
            index=models.Index(fields=['funcion_destino'], name='IDX_int_func_destino'),
        ),
    ]
