# Generated by Django 5.2.6 on 2025-12-01 20:03

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0029_historicalconfiguracioncine'),
        ('ventas', '0030_rename_ventas_inte_venta_i_a3e51e_idx_idx_int_venta_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIntercambio',
            fields=[
                ('id_intercambio', models.IntegerField(blank=True, db_index=True)),
                ('fecha_intercambio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Intercambio')),
                ('motivo', models.CharField(choices=[('HORARIO', 'Cambio de horario'), ('FECHA', 'Cambio de fecha'), ('PELICULA', 'Cambio de película'), ('DISPONIBILIDAD', 'Disponibilidad de asientos'), ('OTRO', 'Otro motivo')], default='OTRO', max_length=20, verbose_name='Motivo del Intercambio')),
                ('estado', models.CharField(choices=[('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido'), ('REVERTIDO', 'Revertido')], default='COMPLETADO', max_length=20, verbose_name='Estado')),
                ('cantidad_entradas', models.IntegerField(help_text='Número de entradas que se intercambiaron', verbose_name='Cantidad de Entradas Intercambiadas')),
                ('penalidad_aplicada', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto de penalidad cobrado (si aplica)', max_digits=10, verbose_name='Penalidad Aplicada')),
                ('notas', models.TextField(blank=True, default='', help_text='Información adicional sobre el intercambio', verbose_name='Notas')),
                ('usuario_email', models.EmailField(help_text='Email del cliente que realizó el intercambio', max_length=254, verbose_name='Email del Usuario')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Intercambio de Entrada',
                'verbose_name_plural': 'historical Intercambios de Entradas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPago',
            fields=[
                ('id_pago', models.IntegerField(blank=True, db_index=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('nro_transaccion', models.CharField(blank=True, default='', help_text='ID de transacción de Mercado Pago u otro procesador', max_length=100, verbose_name='Número de Transacción')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Pago',
                'verbose_name_plural': 'historical Pagos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveIndex(
            model_name='intercambio',
            name='ventas_inte_venta_i_a3e51e_idx',
        ),
        migrations.RemoveIndex(
            model_name='intercambio',
            name='ventas_inte_estado_f7fc6c_idx',
        ),
        migrations.RemoveIndex(
            model_name='intercambio',
            name='ventas_inte_funcion_b26f17_idx',
        ),
        migrations.RemoveIndex(
            model_name='intercambio',
            name='ventas_inte_funcion_75aeec_idx',
        ),
        migrations.AddField(
            model_name='historicalintercambio',
            name='funcion_destino',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cine.funcion', verbose_name='Nueva Función'),
        ),
        migrations.AddField(
            model_name='historicalintercambio',
            name='funcion_origen',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cine.funcion', verbose_name='Función Original'),
        ),
        migrations.AddField(
            model_name='historicalintercambio',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalintercambio',
            name='venta',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.venta', verbose_name='Venta'),
        ),
        migrations.AddField(
            model_name='historicalpago',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpago',
            name='id_metodo_pago',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.metodopago', verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='historicalpago',
            name='id_venta',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.venta', verbose_name='Venta'),
        ),
    ]
