# Generated by Django 5.2.6 on 2025-12-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0031_historicalintercambio_historicalpago_and_more'),
    ]

    operations = [
        # Paso 1: Remover el constraint problemático que incluía valores vacíos
        migrations.RemoveConstraint(
            model_name='venta',
            name='UQ_venta_codigo_compra',
        ),
        
        # Paso 2: Agregar índice único PARCIAL (solo para valores no vacíos)
        # Esto permite múltiples ventas presenciales con codigo_compra=''
        # pero garantiza unicidad para códigos de ventas online
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX ventas_venta_codigo_compra_unique_partial
                ON "Venta" (codigo_compra)
                WHERE codigo_compra != '';
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS ventas_venta_codigo_compra_unique_partial;
            """
        ),
    ]
