# Generated by Django 5.2.6 on 2026-02-03 16:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_cliente_direccion_cliente_acepta_marketing'),
        ('promociones', '0019_historicalcupongenerado_historicalpoliticapromocion_and_more'),
        ('ventas', '0032_fix_codigo_compra_unique_constraint'),
    ]

    operations = [
        # ✅ CORRECCIÓN: Eliminadas operaciones de campos que ya existen o nunca existieron
        # - RemoveField: horas_minimas_antes_evento, is_active, porcentaje_reembolso (nunca existieron)
        # - AddField historicalventa.cupon_utilizado: ya existe desde migración 0013
        
        migrations.AddField(
            model_name='politicareembolso',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si está activa, esta política permite intercambios con las condiciones definidas'),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='dias_antes_minimo',
            field=models.IntegerField(default=1, help_text='Número mínimo de días antes de la función para permitir intercambio'),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='max_cambios_por_compra',
            field=models.IntegerField(default=1, help_text='Máximo de intercambios permitidos por compra (0 = ilimitado)'),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='penalidad_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de penalidad aplicado al intercambio (si aplica)', max_digits=5),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado', 'fecha_compra'], name='idx_venta_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['id_cliente', '-fecha_compra'], name='idx_venta_cliente_fecha'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['tipo_venta', 'estado'], name='idx_venta_tipo_estado'),
        ),
    ]
