# Generated by Django 5.2.6 on 2026-02-04 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0021_add_vinculo_unique_constraints'),
        ('ventas', '0033_remove_politicareembolso_horas_minimas_antes_evento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicareembolso',
            name='horas_minimas_antes_evento',
        ),
        migrations.RemoveField(
            model_name='politicareembolso',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='politicareembolso',
            name='porcentaje_reembolso',
        ),
        migrations.AddField(
            model_name='historicalventa',
            name='cupon_utilizado',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Referencias al cupón usado para esta venta (si aplica)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='promociones.cupongenerado', verbose_name='Cupón Utilizado'),
        ),
    ]
