# Generated by Django 5.2.6 on 2026-02-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0034_remove_politicareembolso_horas_minimas_antes_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalventa',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de la venta calculado y persistido para precisión financiera', max_digits=10, null=True, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de la venta calculado y persistido para precisión financiera', max_digits=10, null=True, verbose_name='Total'),
        ),
    ]
