# Generated by Django 5.2.6 on 2026-02-04 18:08

from django.db import migrations
from decimal import Decimal


def populate_total_ventas(apps, schema_editor):
    """
    Calcula y guarda el total de todas las ventas existentes.
    Usa la lógica del método calcular_total() pero de forma compatible con migraciones.
    """
    Venta = apps.get_model('ventas', 'Venta')
    Entrada = apps.get_model('ventas', 'Entrada')
    
    # Importar el servicio de cálculo de precios
    from promociones.services import calcular_precio_final
    
    ventas_actualizadas = 0
    
    for venta in Venta.objects.all():
        entradas = Entrada.objects.filter(id_venta=venta)
        
        if not entradas.exists():
            venta.total = Decimal('0.00')
            venta.save(update_fields=['total'])
            continue
        
        try:
            cantidad = entradas.count()
            funcion = entradas.first().id_funcion
            
            # Determinar promoción (si tiene cupón)
            promo_obj = None
            if venta.cupon_utilizado:
                politica = getattr(venta.cupon_utilizado, 'politica_origen', None)
                if politica:
                    promo_obj = politica.promocion_a_otorgar
                else:
                    promo_obj = getattr(venta.cupon_utilizado, 'promocion', None)
            
            # Calcular total usando el servicio centralizado
            total_final, _, _ = calcular_precio_final(
                funcion,
                cantidad,
                promocion_especifica=promo_obj
            )
            
            venta.total = total_final
            venta.save(update_fields=['total'])
            ventas_actualizadas += 1
            
        except Exception as e:
            # Si falla, usar precio base * cantidad como fallback
            precio_base = entradas.first().id_funcion.precio_base
            venta.total = Decimal(str(precio_base)) * cantidad
            venta.save(update_fields=['total'])
            ventas_actualizadas += 1
    
    print(f"✅ {ventas_actualizadas} ventas actualizadas con campo total")


def reverse_populate(apps, schema_editor):
    """Reversión: simplemente setear total a NULL"""
    Venta = apps.get_model('ventas', 'Venta')
    Venta.objects.all().update(total=None)


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0035_add_total_field'),
    ]

    operations = [
        migrations.RunPython(populate_total_ventas, reverse_populate),
    ]
