# Generated by Django 5.2.6 on 2026-02-04 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0036_populate_venta_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalventa',
            name='id_metodo_pago',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Método de pago utilizado para la venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.metodopago', verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_metodo_pago',
            field=models.ForeignKey(blank=True, help_text='Método de pago utilizado para la venta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.metodopago', verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='historicalventa',
            name='medio_pago',
            field=models.CharField(blank=True, default='', help_text='Campo legacy - usar id_metodo_pago', max_length=20, verbose_name='Medio de Pago (Legacy)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='medio_pago',
            field=models.CharField(blank=True, default='', help_text='Campo legacy - usar id_metodo_pago', max_length=20, verbose_name='Medio de Pago (Legacy)'),
        ),
    ]
