# Generated by Django 5.2.6 on 2026-02-04 18:17

from django.db import migrations


def migrate_medio_pago_to_fk(apps, schema_editor):
    """
    Migra los valores del campo medio_pago (CharField) a id_metodo_pago (ForeignKey).
    Mapea: EFECTIVO → Efectivo, MERCADOPAGO → Mercado Pago, TARJETA → Tarjeta
    """
    Venta = apps.get_model('ventas', 'Venta')
    MetodoPago = apps.get_model('ventas', 'MetodoPago')
    
    # Mapeo de strings antiguos a nombres de MetodoPago
    mapeo = {
        'EFECTIVO': 'Efectivo',
        'MERCADOPAGO': 'Mercado Pago',
        'TARJETA': 'Tarjeta',
    }
    
    ventas_actualizadas = 0
    
    for venta in Venta.objects.filter(medio_pago__in=mapeo.keys()):
        nombre_metodo = mapeo[venta.medio_pago]
        try:
            metodo = MetodoPago.objects.get(nombre=nombre_metodo)
            venta.id_metodo_pago = metodo
            venta.save(update_fields=['id_metodo_pago'])
            ventas_actualizadas += 1
        except MetodoPago.DoesNotExist:
            # Si el método no existe, crearlo
            metodo = MetodoPago.objects.create(nombre=nombre_metodo)
            venta.id_metodo_pago = metodo
            venta.save(update_fields=['id_metodo_pago'])
            ventas_actualizadas += 1
    
    print(f"✅ {ventas_actualizadas} ventas migradas de medio_pago a id_metodo_pago")


def reverse_migrate(apps, schema_editor):
    """Reversión: copiar de vuelta a medio_pago"""
    Venta = apps.get_model('ventas', 'Venta')
    
    mapeo_inverso = {
        'Efectivo': 'EFECTIVO',
        'Mercado Pago': 'MERCADOPAGO',
        'Tarjeta': 'TARJETA',
    }
    
    for venta in Venta.objects.filter(id_metodo_pago__isnull=False):
        nombre_metodo = venta.id_metodo_pago.nombre
        if nombre_metodo in mapeo_inverso:
            venta.medio_pago = mapeo_inverso[nombre_metodo]
            venta.save(update_fields=['medio_pago'])


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0037_add_id_metodo_pago_fk'),
    ]

    operations = [
        migrations.RunPython(migrate_medio_pago_to_fk, reverse_migrate),
    ]
