# Generated by Django 5.2.6 on 2026-02-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0038_migrate_medio_pago_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalventa',
            name='medio_pago',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='medio_pago',
        ),
    ]
