# Generated by DBA for data consistency cleanup
# This migration ensures data integrity before applying database constraints

from django.db import migrations
from decimal import Decimal


def cleanup_negative_values(apps, schema_editor):
    """
    Limpia valores negativos en Venta.total y Pago.monto antes de aplicar constraints.

    Esta función:
    1. Identifica ventas con totales negativos y los ajusta a 0.00
    2. Identifica pagos con montos negativos y los ajusta a 0.00
    3. Reporta en consola cualquier inconsistencia encontrada
    """
    Venta = apps.get_model('ventas', 'Venta')
    Pago = apps.get_model('ventas', 'Pago')

    # 1. Limpiar ventas con totales negativos
    ventas_negativas = Venta.objects.filter(total__lt=0)
    count_ventas = ventas_negativas.count()

    if count_ventas > 0:
        print(f"\n⚠️  ADVERTENCIA: Se encontraron {count_ventas} ventas con totales negativos.")
        print("   Ajustando a 0.00 para cumplir con constraint de base de datos...")

        for venta in ventas_negativas:
            print(f"   - Venta #{venta.id_venta}: ${venta.total} → $0.00")
            venta.total = Decimal('0.00')
            venta.save(update_fields=['total'])

        print(f"✅ {count_ventas} ventas corregidas.\n")
    else:
        print("✅ No se encontraron ventas con totales negativos.\n")

    # 2. Limpiar pagos con montos negativos
    pagos_negativos = Pago.objects.filter(monto__lt=0)
    count_pagos = pagos_negativos.count()

    if count_pagos > 0:
        print(f"⚠️  ADVERTENCIA: Se encontraron {count_pagos} pagos con montos negativos.")
        print("   Ajustando a 0.00 para cumplir con constraint de base de datos...")

        for pago in pagos_negativos:
            print(f"   - Pago #{pago.id_pago}: ${pago.monto} → $0.00")
            pago.monto = Decimal('0.00')
            pago.save(update_fields=['monto'])

        print(f"✅ {count_pagos} pagos corregidos.\n")
    else:
        print("✅ No se encontraron pagos con montos negativos.\n")


def verify_codigo_compra_uniqueness(apps, schema_editor):
    """
    Verifica que los códigos de compra sean únicos antes de aplicar constraint.

    Si encuentra duplicados, añade un sufijo incremental para hacerlos únicos.
    """
    Venta = apps.get_model('ventas', 'Venta')

    # Buscar códigos duplicados (excluyendo strings vacíos)
    from django.db.models import Count
    duplicados = (
        Venta.objects
        .exclude(codigo_compra='')
        .values('codigo_compra')
        .annotate(count=Count('id_venta'))
        .filter(count__gt=1)
    )

    if duplicados.exists():
        print(f"\n⚠️  ADVERTENCIA: Se encontraron {duplicados.count()} códigos de compra duplicados.")
        print("   Corrigiendo para garantizar unicidad...\n")

        for dup in duplicados:
            codigo = dup['codigo_compra']
            ventas_duplicadas = Venta.objects.filter(codigo_compra=codigo).order_by('id_venta')

            # Dejar la primera venta con el código original, renumerar las demás
            for idx, venta in enumerate(ventas_duplicadas[1:], start=2):
                nuevo_codigo = f"{codigo}-{idx}"
                print(f"   - Venta #{venta.id_venta}: '{codigo}' → '{nuevo_codigo}'")
                venta.codigo_compra = nuevo_codigo
                venta.save(update_fields=['codigo_compra'])

        print("✅ Códigos de compra duplicados corregidos.\n")
    else:
        print("✅ No se encontraron códigos de compra duplicados.\n")


def verify_metodo_pago_relationships(apps, schema_editor):
    """
    Verifica que todas las ventas y pagos con método de pago tengan una
    FK válida (no un campo de texto).

    Esta verificación es informativa ya que la FK ya existe en el modelo actual.
    """
    Venta = apps.get_model('ventas', 'Venta')
    Pago = apps.get_model('ventas', 'Pago')
    MetodoPago = apps.get_model('ventas', 'MetodoPago')

    print("🔍 Verificando integridad referencial de métodos de pago...")

    # Verificar que todos los pagos tengan un método de pago válido
    pagos_sin_metodo = Pago.objects.filter(id_metodo_pago__isnull=True)
    if pagos_sin_metodo.exists():
        print(f"⚠️  ADVERTENCIA: {pagos_sin_metodo.count()} pagos sin método de pago asignado.")
    else:
        print("✅ Todos los pagos tienen un método de pago válido.")

    # Reporte de ventas sin método de pago (es opcional en Venta)
    ventas_sin_metodo = Venta.objects.filter(id_metodo_pago__isnull=True, estado='CONFIRMADA')
    if ventas_sin_metodo.exists():
        print(f"ℹ️  INFO: {ventas_sin_metodo.count()} ventas confirmadas sin método de pago asignado.")
    else:
        print("✅ Todas las ventas confirmadas tienen método de pago.")

    print()


def reverse_cleanup(apps, schema_editor):
    """
    No es necesario revertir la limpieza de datos.
    Los valores ajustados son correcciones permanentes de inconsistencias.
    """
    print("⚠️  No se puede revertir la limpieza de datos (es una corrección permanente).")


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0039_remove_medio_pago_legacy'),
    ]

    operations = [
        migrations.RunPython(
            cleanup_negative_values,
            reverse_cleanup,
        ),
        migrations.RunPython(
            verify_codigo_compra_uniqueness,
            reverse_cleanup,
        ),
        migrations.RunPython(
            verify_metodo_pago_relationships,
            reverse_cleanup,
        ),
    ]
