# Generated by Django 5.2.6 on 2026-02-07 14:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_historicalusuario_email_alter_usuario_email'),
        ('promociones', '0021_add_vinculo_unique_constraints'),
        ('ventas', '0040_data_cleanup_before_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpago',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto del pago - debe ser mayor o igual a cero', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='historicalventa',
            name='codigo_compra',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Código único para canje de entradas (generado automáticamente)', max_length=20, verbose_name='Código de Compra'),
        ),
        migrations.AlterField(
            model_name='historicalventa',
            name='cupon_utilizado',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, help_text='Referencias al cupón usado para esta venta (si aplica)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='promociones.cupongenerado', verbose_name='Cupón Utilizado'),
        ),
        migrations.AlterField(
            model_name='historicalventa',
            name='id_metodo_pago',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, help_text='Método de pago utilizado para la venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.metodopago', verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='historicalventa',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Total de la venta calculado y persistido para precisión financiera', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto del pago - debe ser mayor o igual a cero', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='codigo_compra',
            field=models.CharField(blank=True, default='', editable=False, help_text='Código único para canje de entradas (generado automáticamente)', max_length=20, unique=True, verbose_name='Código de Compra'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cupon_utilizado',
            field=models.ForeignKey(blank=True, editable=False, help_text='Referencias al cupón usado para esta venta (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_usadas', to='promociones.cupongenerado', verbose_name='Cupón Utilizado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_metodo_pago',
            field=models.ForeignKey(blank=True, editable=False, help_text='Método de pago utilizado para la venta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.metodopago', verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Total de la venta calculado y persistido para precisión financiera', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='chk_pago_monto_no_negativo', violation_error_message='El monto del pago no puede ser negativo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0), ('total__isnull', True), _connector='OR'), name='chk_venta_total_no_negativo', violation_error_message='El total de la venta no puede ser negativo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_compra', ''), _negated=True), fields=('codigo_compra',), name='uq_venta_codigo_compra_no_vacio', violation_error_message='El código de compra debe ser único'),
        ),
    ]
