# Generated by Django 5.2.6 on 2026-02-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_historicalusuario_email_alter_usuario_email'),
        ('promociones', '0021_add_vinculo_unique_constraints'),
        ('ventas', '0044_auto_20260207_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Unitario Real'),
        ),
        migrations.AddField(
            model_name='historicalentrada',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Unitario Real'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('codigo_compra', ''), _negated=True), name='chk_venta_codigo_no_vacio'),
        ),
    ]
