# Generated by Django 5.2.6 on 2026-02-07 19:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_historicalusuario_email_alter_usuario_email'),
        ('promociones', '0021_add_vinculo_unique_constraints'),
        ('ventas', '0046_alter_entrada_reservado_por'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='venta',
            name='chk_venta_total_no_negativo',
        ),
        migrations.AlterField(
            model_name='historicalventa',
            name='codigo_compra',
            field=models.CharField(db_index=True, default='', editable=False, help_text='Código único para canje de entradas (generado automáticamente)', max_length=20, verbose_name='Código de Compra'),
        ),
        migrations.AlterField(
            model_name='historicalventa',
            name='id_metodo_pago',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.metodopago', verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='historicalventa',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='codigo_compra',
            field=models.CharField(default='', editable=False, help_text='Código único para canje de entradas (generado automáticamente)', max_length=20, unique=True, verbose_name='Código de Compra'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='accounts.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_metodo_pago',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.metodopago', verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='chk_venta_total_no_negativo', violation_error_message='El total de la venta no puede ser negativo'),
        ),
    ]
