# Generated by Django 5.2.6 on 2026-02-11 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0034_alter_funcion_precio_base_and_more'),
        ('ventas', '0047_remove_venta_chk_venta_total_no_negativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['id_funcion', 'id_butaca', 'estado'], name='idx_lock_butaca'),
        ),
    ]
