# Generated by Django 5.2.6 on 2026-02-28 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0048_entrada_idx_lock_butaca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalintercambio',
            name='penalidad_aplicada',
        ),
        migrations.RemoveField(
            model_name='intercambio',
            name='penalidad_aplicada',
        ),
        migrations.RemoveField(
            model_name='politicareembolso',
            name='penalidad_percent',
        ),
    ]
