# Generated by Django 5.2.6 on 2026-03-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0049_remove_penalidad_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalintercambio',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='historicalintercambio',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='intercambio',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='intercambio',
            name='user_agent',
        ),
    ]
