# Generated by Django 5.2.6 on 2026-03-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0050_remove_ip_useragent_from_intercambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalventa',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si la venta está activa o ha sido dada de baja lógicamente', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='venta',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si la venta está activa o ha sido dada de baja lógicamente', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESERVADA', 'Reservada'), ('VENDIDA', 'Vendida'), ('ENTREGADA', 'Entregada'), ('USADA', 'Usada'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada')], default='RESERVADA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalentrada',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESERVADA', 'Reservada'), ('VENDIDA', 'Vendida'), ('ENTREGADA', 'Entregada'), ('USADA', 'Usada'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada')], default='RESERVADA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalventa',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PENDIENTE_PAGO', 'Pendiente de Pago'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PENDIENTE_PAGO', 'Pendiente de Pago'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
    ]
