# Generated by Django 5.2.6 on 2026-03-05 13:39

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0053_fix_bunker_triggers_vendida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRegistroAcceso',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_hora_intento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora del Intento')),
                ('tipo_validacion', models.CharField(choices=[('QR', 'Escaneo QR'), ('MANUAL', 'Búsqueda Manual'), ('CODIGO', 'Código de Entrada')], default='QR', max_length=10, verbose_name='Tipo de Validación')),
                ('resultado', models.CharField(choices=[('PERMITIDO', 'Acceso Permitido'), ('RECHAZADO', 'Acceso Rechazado')], max_length=10, verbose_name='Resultado')),
                ('codigo_buscado', models.CharField(blank=True, max_length=200, verbose_name='Código/Texto Buscado')),
                ('motivo_rechazo', models.CharField(blank=True, help_text='Por ejemplo: "Función no comenzó", "Ya usada", "No encontrada"', max_length=255, verbose_name='Motivo del Rechazo')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origen')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empleado_validador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Empleado que Validó')),
                ('entrada', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.entrada', verbose_name='Entrada Validada')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Registro de Acceso',
                'verbose_name_plural': 'historical Registros de Acceso',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_intento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora del Intento')),
                ('tipo_validacion', models.CharField(choices=[('QR', 'Escaneo QR'), ('MANUAL', 'Búsqueda Manual'), ('CODIGO', 'Código de Entrada')], default='QR', max_length=10, verbose_name='Tipo de Validación')),
                ('resultado', models.CharField(choices=[('PERMITIDO', 'Acceso Permitido'), ('RECHAZADO', 'Acceso Rechazado')], max_length=10, verbose_name='Resultado')),
                ('codigo_buscado', models.CharField(blank=True, max_length=200, verbose_name='Código/Texto Buscado')),
                ('motivo_rechazo', models.CharField(blank=True, help_text='Por ejemplo: "Función no comenzó", "Ya usada", "No encontrada"', max_length=255, verbose_name='Motivo del Rechazo')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origen')),
                ('empleado_validador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Empleado que Validó')),
                ('entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_acceso', to='ventas.entrada', verbose_name='Entrada Validada')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'db_table': 'RegistroAcceso',
                'ordering': ['-fecha_hora_intento'],
                'indexes': [models.Index(fields=['entrada', 'fecha_hora_intento'], name='idx_acceso_entrada'), models.Index(fields=['resultado', 'fecha_hora_intento'], name='idx_acceso_resultado')],
            },
        ),
    ]
