# Generated by Django 5.2.6 on 2026-03-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0054_historicalregistroacceso_registroacceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el espectador ingresó a la sala.', null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='utilizado',
            field=models.BooleanField(default=False, help_text='True cuando la entrada fue escaneada y validada en la puerta de acceso.', verbose_name='Utilizado'),
        ),
        migrations.AddField(
            model_name='historicalentrada',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el espectador ingresó a la sala.', null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AddField(
            model_name='historicalentrada',
            name='utilizado',
            field=models.BooleanField(default=False, help_text='True cuando la entrada fue escaneada y validada en la puerta de acceso.', verbose_name='Utilizado'),
        ),
    ]
