# Generated by Django 5.2.6 on 2026-03-12 01:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0051_entrada_unique_constraint_condicional'),
        ('ventas', '0055_entrada_fecha_ingreso_entrada_utilizado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entrada',
            name='UQ_entrada_funcion_butaca',
        ),
        migrations.AddConstraint(
            model_name='entrada',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'RESERVADA', 'VENDIDA', 'ENTREGADA', 'USADA'])), fields=('id_funcion', 'id_butaca'), name='UQ_entrada_funcion_butaca_activa'),
        ),
    ]
