# Generated by Django 5.2.6 on 2026-03-12 01:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0056_entrada_unique_constraint_condicional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fondo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Efectivo disponible al abrir la caja', max_digits=10, verbose_name='Fondo Inicial (efectivo)')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones al cierre')),
                ('total_efectivo_cerrado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Efectivo (cierre)')),
                ('total_qr_cerrado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total QR (cierre)')),
                ('total_ventas_cerrado', models.IntegerField(blank=True, null=True, verbose_name='Cantidad Ventas (cierre)')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_caja', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'db_table': 'CajaSesion',
                'ordering': ['-fecha_apertura'],
            },
        ),
    ]
