# Generated by Django 5.2.6 on 2026-03-12 02:49

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0057_add_cajasesion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cajasesion',
            name='diferencia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Positivo = sobrante, Negativo = faltante.', max_digits=10, null=True, verbose_name='Diferencia (Real − Esperado)'),
        ),
        migrations.AddField(
            model_name='cajasesion',
            name='monto_esperado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fondo inicial + efectivo cobrado (calculado por el sistema).', max_digits=10, null=True, verbose_name='Monto Esperado en Caja'),
        ),
        migrations.AddField(
            model_name='cajasesion',
            name='monto_real_declarado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lo que el empleado contó en la caja al cerrar.', max_digits=10, null=True, verbose_name='Efectivo Físico Contado'),
        ),
        migrations.CreateModel(
            name='HistoricalCajaSesion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fondo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Efectivo disponible al abrir la caja', max_digits=10, verbose_name='Fondo Inicial (efectivo)')),
                ('fecha_apertura', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones al cierre')),
                ('total_efectivo_cerrado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Efectivo (cierre)')),
                ('total_qr_cerrado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total QR (cierre)')),
                ('total_ventas_cerrado', models.IntegerField(blank=True, null=True, verbose_name='Cantidad Ventas (cierre)')),
                ('monto_esperado', models.DecimalField(blank=True, decimal_places=2, help_text='Fondo inicial + efectivo cobrado (calculado por el sistema).', max_digits=10, null=True, verbose_name='Monto Esperado en Caja')),
                ('monto_real_declarado', models.DecimalField(blank=True, decimal_places=2, help_text='Lo que el empleado contó en la caja al cerrar.', max_digits=10, null=True, verbose_name='Efectivo Físico Contado')),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, help_text='Positivo = sobrante, Negativo = faltante.', max_digits=10, null=True, verbose_name='Diferencia (Real − Esperado)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empleado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Sesión de Caja',
                'verbose_name_plural': 'historical Sesiones de Caja',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
