# Generated by Django 5.2.6 on 2026-03-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0058_cajasesion_arqueo_historical'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalventa',
            name='email_invitado',
            field=models.EmailField(blank=True, help_text='Correo del comprador cuando no tiene cuenta registrada (ventas presenciales)', max_length=254, null=True, verbose_name='Email Invitado'),
        ),
        migrations.AddField(
            model_name='venta',
            name='email_invitado',
            field=models.EmailField(blank=True, help_text='Correo del comprador cuando no tiene cuenta registrada (ventas presenciales)', max_length=254, null=True, verbose_name='Email Invitado'),
        ),
    ]
