# Generated by Django 5.2.6 on 2026-03-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0059_email_invitado_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicareembolso',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue dado de baja', null=True, verbose_name='Fecha de Baja'),
        ),
    ]
