# Generated by Django 5.2.6 on 2026-03-14 17:37

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0060_politicareembolso_fecha_baja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='politicareembolso',
            name='ofrecer_promos_vinculo',
            field=models.BooleanField(default=False, help_text='Si está activo, al elegir la nueva función se consideran promociones de vínculo específico.'),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='permitir_con_cupon_promocion',
            field=models.BooleanField(default=False, help_text='Permite intercambiar compras realizadas con cupón o promoción de vínculo específico.'),
        ),
        migrations.AddField(
            model_name='politicareembolso',
            name='permitir_reintercambio',
            field=models.BooleanField(default=False, help_text='Permite realizar un nuevo intercambio sobre una compra que ya tuvo intercambio previo.'),
        ),
        migrations.CreateModel(
            name='HistoricalPoliticaReembolso',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_baja', models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue dado de baja', null=True, verbose_name='Fecha de Baja')),
                ('nombre', models.CharField(default='Política de Intercambio', max_length=140)),
                ('activo', models.BooleanField(default=True, help_text='Si está activa, esta política permite intercambios con las condiciones definidas')),
                ('dias_antes_minimo', models.IntegerField(default=1, help_text='Número mínimo de días antes de la función para permitir intercambio')),
                ('max_cambios_por_compra', models.IntegerField(default=1, help_text='Máximo de intercambios permitidos por compra (0 = ilimitado)')),
                ('ofrecer_promos_vinculo', models.BooleanField(default=False, help_text='Si está activo, al elegir la nueva función se consideran promociones de vínculo específico.')),
                ('permitir_reintercambio', models.BooleanField(default=False, help_text='Permite realizar un nuevo intercambio sobre una compra que ya tuvo intercambio previo.')),
                ('permitir_con_cupon_promocion', models.BooleanField(default=False, help_text='Permite intercambiar compras realizadas con cupón o promoción de vínculo específico.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Política de Reembolso/Intercambio',
                'verbose_name_plural': 'historical Políticas de Reembolso/Intercambio',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
