# Generated by Django 5.2.6 on 2025-11-19 21:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_historicalusuario'),
        ('cine', '0016_historicalfuncion_historicalpelicula_historicalsala'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('genero_trigger', models.CharField(blank=True, help_text='Género de película que activa esta política (opcional)', max_length=50, null=True)),
                ('hora_inicio_rango', models.TimeField(help_text='Hora de inicio del rango (ej: 18:00)')),
                ('hora_fin_rango', models.TimeField(help_text='Hora de fin del rango (ej: 23:00)')),
            ],
            options={
                'verbose_name': 'Política de Promoción',
                'verbose_name_plural': 'Políticas de Promoción',
                'db_table': 'promociones_politicapromocion',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_descuento', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('2X1', '2x1'), ('MONTO_FIJO', 'Monto fijo')], max_length=20)),
                ('valor_descuento', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje (0-100) o monto fijo. No se usa para 2x1.', max_digits=8, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'promociones_promocion',
            },
        ),
        migrations.CreateModel(
            name='CuponGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cupones', to='accounts.cliente')),
                ('politica_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cupones_generados', to='promociones.politicapromocion')),
            ],
            options={
                'db_table': 'promociones_cupongenerado',
            },
        ),
        migrations.AddField(
            model_name='politicapromocion',
            name='promocion_a_otorgar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='promociones.promocion'),
        ),
        migrations.CreateModel(
            name='FuncionPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='cine.funcion')),
                ('pelicula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='cine.pelicula')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones_asociadas', to='promociones.promocion')),
            ],
            options={
                'db_table': 'promociones_funcionpromocion',
                'unique_together': {('promocion', 'funcion', 'pelicula')},
            },
        ),
    ]
