# Generated by Django 5.2.6 on 2025-11-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicapromocion',
            name='genero_trigger',
        ),
        migrations.AddField(
            model_name='politicapromocion',
            name='genero_pelicula',
            field=models.CharField(blank=True, choices=[('ACCION', 'Acción'), ('AVENTURA', 'Aventura'), ('COMEDIA', 'Comedia'), ('DRAMA', 'Drama'), ('CIENCIA_FICCION', 'Ciencia Ficción'), ('TERROR', 'Terror'), ('FANTASIA', 'Fantasía'), ('MUSICAL', 'Musical'), ('ANIMACION', 'Animación')], help_text='Género de película que activa esta política (opcional)', max_length=50, null=True),
        ),
    ]
