# Generated by Django 5.2.6 on 2025-11-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0002_remove_politicapromocion_genero_trigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicapromocion',
            name='dias_semana',
            field=models.JSONField(blank=True, help_text='Lista de días de la semana en que aplica la política (0=Lunes,..6=Domingo). Dejar vacío para todos los días.', null=True),
        ),
    ]
