# Generated by Django 5.2.6 on 2025-11-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0003_politicapromocion_dias_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupongenerado',
            name='expira_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politicapromocion',
            name='minutos_validez',
            field=models.PositiveIntegerField(default=60, help_text='Minutos que el enlace del cupón será válido'),
        ),
        migrations.AddField(
            model_name='politicapromocion',
            name='prioridad',
            field=models.PositiveIntegerField(default=0, help_text='Prioridad de la política (mayor gana)'),
        ),
        migrations.AlterField(
            model_name='politicapromocion',
            name='dias_semana',
            field=models.CharField(blank=True, default='', help_text='Días permitidos como CSV de índices (0=Lunes,..6=Domingo). Ej: "0,2,4"', max_length=32),
        ),
    ]
