# Generated by Django 5.2.6 on 2025-11-20 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0020_remove_historicalpelicula_genero_alter_genero_id'),
        ('promociones', '0005_genero_fk_and_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicapromocion',
            name='genero_pelicula',
            field=models.ForeignKey(blank=True, help_text='Género de película que activa esta política (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='politicas', to='cine.genero'),
        ),
    ]
