# Generated by Django 5.2.6 on 2025-11-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0006_alter_politicapromocion_genero_pelicula'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='es_automatica',
            field=models.BooleanField(default=False, help_text='Si está marcada, la promoción se aplicará automáticamente a funciones vinculadas.'),
        ),
    ]
