# Generated by Django 5.2.6 on 2025-11-21 00:28

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0007_promocion_es_automatica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicapromocion',
            name='dias_semana',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', 'Lunes'), ('1', 'Martes'), ('2', 'Miércoles'), ('3', 'Jueves'), ('4', 'Viernes'), ('5', 'Sábado'), ('6', 'Domingo')], default='', help_text='Selecciona los días de la semana en los que la política aplica (solo para promociones automáticas).', max_length=14, null=True),
        ),
    ]
