# Generated by Django 5.2.6 on 2025-11-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0008_alter_politicapromocion_dias_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicapromocion',
            name='dias_semana',
            field=models.CharField(blank=True, default='', help_text='Días permitidos como CSV de índices (0=Lunes,..6=Domingo). Ej: "0,2,4"', max_length=32),
        ),
    ]
