# Generated by Django 5.2.6 on 2025-11-21 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0021_historicalpelicula_acepta_promociones_and_more'),
        ('promociones', '0009_alter_politicapromocion_dias_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='aplica_en_estrenos',
            field=models.BooleanField(default=False, help_text='Si es True, ignora el flag es_estreno de la película.'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='genero_requerido',
            field=models.ForeignKey(blank=True, help_text='Si es None, aplica a todos los géneros. Si tiene valor, solo aplica a ese género.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine.genero'),
        ),
    ]
