# Generated by Django 5.2.6 on 2025-11-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0010_promocion_aplica_en_estrenos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='dias_semana',
            field=models.CharField(blank=True, default='', help_text='Días permitidos como CSV de índices (0=Lunes,..6=Domingo). Ej: "0,2,4". Vacío = todos los días.', max_length=32),
        ),
    ]
