# Generated by Django 5.2.6 on 2025-11-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0012_add_funcion_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicapromocion',
            name='horas_antes_de_funcion',
            field=models.PositiveIntegerField(blank=True, help_text='Horas mínimas antes de la función para disparar el envío. Si no se define, envía siempre.', null=True),
        ),
    ]
