# Generated by Django 5.2.6 on 2025-11-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0013_politicapromocion_horas_antes_de_funcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicapromocion',
            name='prioridad',
            field=models.PositiveIntegerField(default=100, help_text='Prioridad de la política (1 = mayor prioridad; ordenar ascendente). Valor por defecto=100 (baja prioridad)'),
        ),
    ]
