# Generated by Django 5.2.6 on 2025-11-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0014_alter_politicapromocion_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicapromocion',
            name='activar_por_ocupacion',
            field=models.BooleanField(default=False, help_text='Si está activo, el sistema escaneará automáticamente funciones futuras y disparará promociones cuando la ocupación sea baja.'),
        ),
        migrations.AddField(
            model_name='politicapromocion',
            name='horas_anticipacion',
            field=models.PositiveIntegerField(default=24, help_text='Analizar funciones que ocurran dentro de X horas. El sistema verificará funciones en este rango de tiempo.'),
        ),
        migrations.AddField(
            model_name='politicapromocion',
            name='umbral_ocupacion',
            field=models.PositiveIntegerField(default=30, help_text='Porcentaje de ocupación mínimo para activar promociones automáticas (ej: 30 = disparar si ocupación < 30%)'),
        ),
    ]
