# Generated by Django 5.2.6 on 2025-12-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0015_yield_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicapromocion',
            name='prioridad',
            field=models.PositiveIntegerField(default=100, help_text='Prioridad de la política: 1 = máxima prioridad, números más altos = menor prioridad. Valor por defecto=100 (baja prioridad)'),
        ),
    ]
