# Generated by Django 5.2.6 on 2025-12-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0016_remove_vip_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
