# Generated by Django 5.2.6 on 2025-12-01 19:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_cliente_direccion_cliente_acepta_marketing'),
        ('cine', '0028_rename_cine_butaca_sala_id_1c63a7_idx_idx_butaca_sala_fila_numero_and_more'),
        ('promociones', '0017_alter_promocion_descripcion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='funcionpromocion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cupongenerado',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='cupongenerado',
            constraint=models.UniqueConstraint(fields=('token',), name='UQ_cupongenerado_token'),
        ),
        migrations.AddConstraint(
            model_name='funcionpromocion',
            constraint=models.UniqueConstraint(fields=('promocion', 'funcion', 'pelicula'), name='UQ_funcionpromocion_promocion_funcion_pelicula'),
        ),
        migrations.AddConstraint(
            model_name='promocion',
            constraint=models.UniqueConstraint(fields=('codigo',), name='UQ_promocion_codigo'),
        ),
    ]
