# Generated by Django 5.2.6 on 2025-12-01 20:03

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_cliente_direccion_cliente_acepta_marketing'),
        ('cine', '0029_historicalconfiguracioncine'),
        ('promociones', '0018_alter_funcionpromocion_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCuponGenerado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('usado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.cliente')),
                ('funcion_origen', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cine.funcion')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('politica_origen', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='promociones.politicapromocion')),
            ],
            options={
                'verbose_name': 'historical cupon generado',
                'verbose_name_plural': 'historical cupon generados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPoliticaPromocion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('hora_inicio_rango', models.TimeField(help_text='Hora de inicio del rango (ej: 18:00)')),
                ('hora_fin_rango', models.TimeField(help_text='Hora de fin del rango (ej: 23:00)')),
                ('dias_semana', models.CharField(blank=True, default='', help_text='Días permitidos como CSV de índices (0=Lunes,..6=Domingo). Ej: "0,2,4"', max_length=32)),
                ('prioridad', models.PositiveIntegerField(default=100, help_text='Prioridad de la política: 1 = máxima prioridad, números más altos = menor prioridad. Valor por defecto=100 (baja prioridad)')),
                ('minutos_validez', models.PositiveIntegerField(default=60, help_text='Minutos que el enlace del cupón será válido')),
                ('horas_antes_de_funcion', models.PositiveIntegerField(blank=True, help_text='Horas mínimas antes de la función para disparar el envío. Si no se define, envía siempre.', null=True)),
                ('activar_por_ocupacion', models.BooleanField(default=False, help_text='Si está activo, el sistema escaneará automáticamente funciones futuras y disparará promociones cuando la ocupación sea baja.')),
                ('umbral_ocupacion', models.PositiveIntegerField(default=30, help_text='Porcentaje de ocupación mínimo para activar promociones automáticas (ej: 30 = disparar si ocupación < 30%)')),
                ('horas_anticipacion', models.PositiveIntegerField(default=24, help_text='Analizar funciones que ocurran dentro de X horas. El sistema verificará funciones en este rango de tiempo.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('genero_pelicula', models.ForeignKey(blank=True, db_constraint=False, help_text='Género de película que activa esta política (opcional)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cine.genero')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('promocion_a_otorgar', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='promociones.promocion')),
            ],
            options={
                'verbose_name': 'historical Política de Promoción',
                'verbose_name_plural': 'historical Políticas de Promoción',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPromocion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('es_automatica', models.BooleanField(default=False, help_text='Si está marcada, la promoción se aplicará automáticamente a funciones vinculadas.')),
                ('tipo_descuento', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('2X1', '2x1'), ('MONTO_FIJO', 'Monto fijo')], max_length=20)),
                ('valor_descuento', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje (0-100) o monto fijo. No se usa para 2x1.', max_digits=8, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('aplica_en_estrenos', models.BooleanField(default=False, help_text='Si es True, ignora el flag es_estreno de la película.')),
                ('dias_semana', models.CharField(blank=True, default='', help_text='Días permitidos como CSV de índices (0=Lunes,..6=Domingo). Ej: "0,2,4". Vacío = todos los días.', max_length=32)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('genero_requerido', models.ForeignKey(blank=True, db_constraint=False, help_text='Si es None, aplica a todos los géneros. Si tiene valor, solo aplica a ese género.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cine.genero')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Promoción',
                'verbose_name_plural': 'historical Promociones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
