# Generated by Django 5.2.6 on 2026-02-03 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0031_alter_funcion_estado_alter_historicalfuncion_estado'),
        ('promociones', '0019_historicalcupongenerado_historicalpoliticapromocion_and_more'),
    ]

    operations = [
        # ✅ RENAME MODEL (solo cambia metadata de Django, NO toca DB)
        migrations.RenameModel(
            old_name='FuncionPromocion',
            new_name='VinculoPromocional',
        ),
        
        # ✅ ACTUALIZAR related_name de promocion FK
        migrations.AlterField(
            model_name='vinculopromocional',
            name='promocion',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='vinculos',  # Antes: funciones_asociadas
                to='promociones.promocion'
            ),
        ),
        
        # ✅ ACTUALIZAR related_name de funcion FK
        migrations.AlterField(
            model_name='vinculopromocional',
            name='funcion',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='promociones_vinculadas',  # Antes: promociones
                to='cine.funcion'
            ),
        ),
        
        # ✅ ACTUALIZAR related_name de pelicula FK
        migrations.AlterField(
            model_name='vinculopromocional',
            name='pelicula',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='promociones_vinculadas',  # Antes: promociones
                to='cine.pelicula'
            ),
        ),
        
        # ✅ AGREGAR verbose_name y verbose_name_plural (metadata Django)
        migrations.AlterModelOptions(
            name='vinculopromocional',
            options={
                'verbose_name': 'Vínculo Promocional',
                'verbose_name_plural': 'Vínculos Promocionales',
            },
        ),
        
        # ✅ AGREGAR CheckConstraint (NUEVA restricción en DB)
        migrations.AddConstraint(
            model_name='vinculopromocional',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('funcion__isnull', True), ('pelicula__isnull', False)),
                    models.Q(('funcion__isnull', False), ('pelicula__isnull', True)),
                    _connector='OR'
                ),
                name='check_vinculo_exactamente_uno'
            ),
        ),
    ]
