# Generated by Django 5.2.6 on 2026-02-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0031_alter_funcion_estado_alter_historicalfuncion_estado'),
        ('promociones', '0020_rename_funcionpromocion_to_vinculopromocional'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vinculopromocional',
            name='UQ_funcionpromocion_promocion_funcion_pelicula',
        ),
        migrations.AddConstraint(
            model_name='vinculopromocional',
            constraint=models.UniqueConstraint(condition=models.Q(('funcion__isnull', False)), fields=('promocion', 'funcion'), name='UQ_vinculo_promocion_funcion'),
        ),
        migrations.AddConstraint(
            model_name='vinculopromocional',
            constraint=models.UniqueConstraint(condition=models.Q(('pelicula__isnull', False)), fields=('promocion', 'pelicula'), name='UQ_vinculo_promocion_pelicula'),
        ),
    ]
