# Generated by Django 5.2.6 on 2026-02-08 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0032_remove_funcion_promocion_aplicada_and_more'),
        ('promociones', '0021_add_vinculo_unique_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupongenerado',
            name='funcion_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupones_generados', to='cine.funcion'),
        ),
        migrations.AlterField(
            model_name='historicalpoliticapromocion',
            name='horas_antes_de_funcion',
            field=models.PositiveIntegerField(default=24, help_text='Horas mínimas antes de la función para disparar el envío. Si no se define, envía siempre.'),
        ),
        migrations.AlterField(
            model_name='historicalpromocion',
            name='valor_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='politicapromocion',
            name='horas_antes_de_funcion',
            field=models.PositiveIntegerField(default=24, help_text='Horas mínimas antes de la función para disparar el envío. Si no se define, envía siempre.'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='valor_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
