# Generated by Django 5.2.6 on 2026-02-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0022_alter_cupongenerado_funcion_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpromocion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
