# Generated by Django 5.2.6 on 2026-02-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0023_historicalpromocion_activo_promocion_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpromocion',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue dado de baja', null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue dado de baja', null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AlterField(
            model_name='historicalpromocion',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o fue dado de baja lógicamente', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o fue dado de baja lógicamente', verbose_name='Activo'),
        ),
    ]
