# Generated by Django 5.2.6 on 2026-03-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0040_funcion_fecha_activacion'),
        ('promociones', '0024_add_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='formatos_aplicables',
            field=models.ManyToManyField(blank=True, help_text='Formatos de proyección a los que aplica esta promoción. Vacío = todos los formatos.', related_name='promociones_aplicables', to='cine.formato'),
        ),
        migrations.AlterField(
            model_name='historicalpoliticapromocion',
            name='activar_por_ocupacion',
            field=models.BooleanField(default=False, help_text='⚡ Habilitar análisis automático: el sistema escaneará funciones futuras y disparará promociones cuando la ocupación sea baja'),
        ),
        migrations.AlterField(
            model_name='historicalpoliticapromocion',
            name='horas_antes_de_funcion',
            field=models.PositiveIntegerField(default=24, help_text='Mínimo de horas antes de la función para disparar el envío de cupones'),
        ),
        migrations.AlterField(
            model_name='historicalpoliticapromocion',
            name='horas_anticipacion',
            field=models.PositiveIntegerField(default=24, help_text='Ventana de tiempo: analizar funciones que ocurran en las próximas X horas desde ahora'),
        ),
        migrations.AlterField(
            model_name='historicalpoliticapromocion',
            name='minutos_validez',
            field=models.PositiveIntegerField(default=60, help_text='Tiempo en minutos que el cupón será válido desde que se envía al cliente'),
        ),
        migrations.AlterField(
            model_name='historicalpoliticapromocion',
            name='umbral_ocupacion',
            field=models.PositiveIntegerField(default=30, help_text='Activar promoción si ocupación < X%. Ejemplo: 30 = activar cuando ocupación sea menor a 30%'),
        ),
        migrations.AlterField(
            model_name='politicapromocion',
            name='activar_por_ocupacion',
            field=models.BooleanField(default=False, help_text='⚡ Habilitar análisis automático: el sistema escaneará funciones futuras y disparará promociones cuando la ocupación sea baja'),
        ),
        migrations.AlterField(
            model_name='politicapromocion',
            name='horas_antes_de_funcion',
            field=models.PositiveIntegerField(default=24, help_text='Mínimo de horas antes de la función para disparar el envío de cupones'),
        ),
        migrations.AlterField(
            model_name='politicapromocion',
            name='horas_anticipacion',
            field=models.PositiveIntegerField(default=24, help_text='Ventana de tiempo: analizar funciones que ocurran en las próximas X horas desde ahora'),
        ),
        migrations.AlterField(
            model_name='politicapromocion',
            name='minutos_validez',
            field=models.PositiveIntegerField(default=60, help_text='Tiempo en minutos que el cupón será válido desde que se envía al cliente'),
        ),
        migrations.AlterField(
            model_name='politicapromocion',
            name='umbral_ocupacion',
            field=models.PositiveIntegerField(default=30, help_text='Activar promoción si ocupación < X%. Ejemplo: 30 = activar cuando ocupación sea menor a 30%'),
        ),
    ]
