# Generated by Django 5.2.6 on 2026-03-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0025_promocion_formatos_aplicables_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpoliticapromocion',
            name='horas_anticipacion',
        ),
        migrations.RemoveField(
            model_name='politicapromocion',
            name='horas_anticipacion',
        ),
        migrations.AlterField(
            model_name='historicalpoliticapromocion',
            name='horas_antes_de_funcion',
            field=models.PositiveIntegerField(default=24, help_text='Horas antes de la función para disparar envío. También se usa como ventana de búsqueda para análisis de ocupación automática (ej: 24 = enviar/analizar si faltan <= 24 horas)'),
        ),
        migrations.AlterField(
            model_name='historicalpoliticapromocion',
            name='prioridad',
            field=models.PositiveIntegerField(default=1, help_text='Prioridad de la política: 1 = máxima prioridad, números más altos = menor prioridad. Valor por defecto=100 (baja prioridad)'),
        ),
        migrations.AlterField(
            model_name='politicapromocion',
            name='horas_antes_de_funcion',
            field=models.PositiveIntegerField(default=24, help_text='Horas antes de la función para disparar envío. También se usa como ventana de búsqueda para análisis de ocupación automática (ej: 24 = enviar/analizar si faltan <= 24 horas)'),
        ),
        migrations.AlterField(
            model_name='politicapromocion',
            name='prioridad',
            field=models.PositiveIntegerField(default=1, help_text='Prioridad de la política: 1 = máxima prioridad, números más altos = menor prioridad. Valor por defecto=100 (baja prioridad)'),
        ),
    ]
