# Generated by Django 5.2.6 on 2025-10-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_administrador_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(help_text='Dirección de email única para cada usuario', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
