# Generated by Django 5.2.6 on 2025-11-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_historicalusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='acepta_marketing',
            field=models.BooleanField(default=False, help_text='Opt-in para recibir novedades y ofertas', verbose_name='Acepta marketing'),
        ),
    ]
