# Generated by Django 5.2.6 on 2026-02-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_cliente_direccion_cliente_acepta_marketing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuario',
            name='email',
            field=models.EmailField(db_index=True, help_text='Dirección de email única', max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(help_text='Dirección de email única', max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
    ]
