# Generated by Django 5.2.6 on 2026-02-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_historicalusuario_email_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='historicalusuario',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el usuario fue dado de baja', null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el usuario fue dado de baja', null=True, verbose_name='Fecha de Baja'),
        ),
    ]
