# Generated by Django 5.2.6 on 2026-03-04 20:29

import accounts.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_fecha_baja_usuario'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', accounts.models.ActiveUserManager()),
                ('all_objects', accounts.models.AllUsersManager()),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Debe ser una fecha entre el 1/1/1900 y hoy', null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(help_text='La fecha de ingreso no puede ser posterior al día de hoy.', validators=[accounts.models.validar_fecha_ingreso_no_futura]),
        ),
        migrations.AlterField(
            model_name='historicalusuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Formato: +54 9 11 1234-5678 o 1112345678 (7-15 dígitos)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='telefono_invalido', message='El teléfono debe contener entre 7 y 15 dígitos numéricos. Puede incluir + al inicio.', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Formato: +54 9 11 1234-5678 o 1112345678 (7-15 dígitos)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='telefono_invalido', message='El teléfono debe contener entre 7 y 15 dígitos numéricos. Puede incluir + al inicio.', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
