# Generated by Django 5.2.6 on 2026-03-04 20:29

from django.db import migrations
from datetime import date


def update_null_fecha_registro(apps, schema_editor):
    """Actualizar todos los registros de Cliente con fecha_registro null"""
    Cliente = apps.get_model('accounts', 'Cliente')
    # Actualizar registros con fecha_registro null
    Cliente.objects.filter(fecha_registro__isnull=True).update(fecha_registro=date.today())


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.RunPython(update_null_fecha_registro, reverse_code=migrations.RunPython.noop),
    ]
