# Generated by Django 5.2.6 on 2026-03-12 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usuario',
            name='email_unico',
        ),
        migrations.RemoveConstraint(
            model_name='usuario',
            name='dni_unico',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='nivel_acceso',
        ),
        migrations.AlterField(
            model_name='historicalusuario',
            name='dni',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El DNI debe contener entre 7 y 8 dígitos numéricos, sin letras ni espacios.', regex='^\\d{7,8}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe contener entre 7 y 8 dígitos numéricos, sin letras ni espacios.', regex='^\\d{7,8}$')]),
        ),
    ]
