# Generated by Django 5.2.6 on 2025-10-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='El título de la película.', max_length=200)),
                ('sinopsis', models.TextField(help_text='Una breve descripción de la trama.')),
                ('director', models.CharField(help_text='El director de la película.', max_length=100)),
                ('genero', models.CharField(choices=[('ACCION', 'Acción'), ('AVENTURA', 'Aventura'), ('COMEDIA', 'Comedia'), ('DRAMA', 'Drama'), ('CIENCIA_FICCION', 'Ciencia Ficción'), ('TERROR', 'Terror'), ('FANTASIA', 'Fantasía'), ('MUSICAL', 'Musical'), ('ANIMACION', 'Animación')], help_text='El género principal.', max_length=50)),
                ('duracion', models.PositiveIntegerField(help_text='La duración en minutos.')),
                ('fecha_estreno', models.DateField(help_text='La fecha de estreno en cines.')),
                ('imagen_portada', models.ImageField(blank=True, help_text='La imagen de portada o póster de la película.', null=True, upload_to='portadas_peliculas/')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-fecha_estreno', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número único de la sala (ej: 1, 2, 3...)', unique=True)),
                ('nombre', models.CharField(help_text="Nombre descriptivo de la sala (ej: 'Sala Premium A')", max_length=100)),
                ('capacidad', models.PositiveIntegerField(help_text='Número total de asientos en la sala')),
                ('tipo', models.CharField(choices=[('NORMAL', 'Sala Normal'), ('VIP', 'Sala VIP'), ('IMAX', 'Sala IMAX'), ('4DX', 'Sala 4DX'), ('DOLBY_ATMOS', 'Dolby Atmos')], default='NORMAL', help_text='Tipo de sala y experiencia que ofrece', max_length=20)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la sala está disponible para proyecciones')),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base de entrada para esta sala', max_digits=8)),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la sala (equipamiento, mantenimiento, etc.)', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['numero'],
            },
        ),
    ]
