# Generated by Django 5.2.6 on 2025-10-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='El título de la película.', max_length=200)),
                ('sinopsis', models.TextField(help_text='Una breve descripción de la trama.')),
                ('director', models.CharField(help_text='El director de la película.', max_length=100)),
                ('genero', models.CharField(choices=[('ACCION', 'Acción'), ('AVENTURA', 'Aventura'), ('COMEDIA', 'Comedia'), ('DRAMA', 'Drama'), ('CIENCIA_FICCION', 'Ciencia Ficción'), ('TERROR', 'Terror'), ('FANTASIA', 'Fantasía'), ('MUSICAL', 'Musical'), ('ANIMACION', 'Animación')], help_text='El género principal.', max_length=50)),
                ('duracion', models.PositiveIntegerField(help_text='La duración en minutos.')),
                ('fecha_estreno', models.DateField(help_text='La fecha de estreno en cines.')),
                ('imagen_portada', models.ImageField(blank=True, help_text='La imagen de portada o póster de la película.', null=True, upload_to='portadas_peliculas/')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-fecha_estreno', 'titulo'],
            },
        ),
    ]
