# Generated by Django 5.2.6 on 2025-10-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pelicula',
            table='peliculas',
        ),
        migrations.AlterModelTable(
            name='sala',
            table='salas',
        ),
    ]
