# Generated by Django 5.2.6 on 2025-10-22 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0002_alter_pelicula_table_alter_sala_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(help_text='Fecha y hora de inicio de la función')),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base de la entrada para esta función (puede variar del precio de la sala)', max_digits=8)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pelicula', models.ForeignKey(help_text='La película que se proyectará en esta función', on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='cine.pelicula')),
                ('sala', models.ForeignKey(help_text='La sala donde se proyectará la función', on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='cine.sala')),
            ],
            options={
                'verbose_name': 'Función',
                'verbose_name_plural': 'Funciones',
                'db_table': 'funciones',
                'ordering': ['fecha_hora', 'sala__numero'],
                'indexes': [models.Index(fields=['fecha_hora', 'sala'], name='funciones_fecha_h_ce0ee9_idx'), models.Index(fields=['pelicula', 'fecha_hora'], name='funciones_pelicul_94f0ff_idx')],
            },
        ),
    ]
