# Generated by Django 5.2.6 on 2025-10-22 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0003_funcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='precio_base',
        ),
    ]
