# Generated by Django 5.2.6 on 2025-10-23 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0004_remove_sala_precio_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='Butaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(help_text='Fila de la butaca (ej: A, B, C, AA, BB)', max_length=5)),
                ('numero', models.PositiveIntegerField(help_text='Número de asiento en la fila')),
                ('tipo', models.CharField(choices=[('GENERAL', 'General'), ('VIP', 'VIP'), ('DISCAPACITADO', 'Discapacitado')], default='GENERAL', help_text='Tipo de butaca', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('sala', models.ForeignKey(help_text='La sala a la que pertenece esta butaca', on_delete=django.db.models.deletion.CASCADE, related_name='butacas', to='cine.sala')),
            ],
            options={
                'verbose_name': 'Butaca',
                'verbose_name_plural': 'Butacas',
                'ordering': ['sala', 'fila', 'numero'],
                'indexes': [models.Index(fields=['sala', 'fila', 'numero'], name='cine_butaca_sala_id_1c63a7_idx')],
                'unique_together': {('sala', 'fila', 'numero')},
            },
        ),
    ]
