# Generated by Django 5.2.6 on 2025-10-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0005_butaca'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='formato_proyeccion',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('4D', '4D'), ('IMAX', 'IMAX'), ('2D_3D', '2D + 3D'), ('2D_4D', '2D + 4D'), ('3D_4D', '3D + 4D')], default='2D', help_text='Formato en el que se proyectará la película', max_length=10),
        ),
        migrations.AlterField(
            model_name='butaca',
            name='tipo',
            field=models.CharField(choices=[('GENERAL', 'General'), ('VIP', 'VIP'), ('DISCAPACITADO', 'Discapacitado'), ('4D', '4D')], default='GENERAL', help_text='Tipo de butaca', max_length=20),
        ),
    ]
