# Generated by Django 5.2.6 on 2025-11-03 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0006_funcion_formato_proyeccion_alter_butaca_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del formato (ej: 2D, 3D, IMAX, 4DX)', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del formato de proyección')),
            ],
            options={
                'verbose_name': 'Formato de Proyección',
                'verbose_name_plural': 'Formatos de Proyección',
                'db_table': 'formato',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='funcion',
            name='formato_proyeccion',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='tipo',
        ),
        migrations.CreateModel(
            name='FuncionFormato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.ForeignKey(help_text='El formato de proyección disponible', on_delete=django.db.models.deletion.PROTECT, related_name='funciones_formato', to='cine.formato')),
                ('funcion', models.ForeignKey(help_text='La función a la que pertenece este formato', on_delete=django.db.models.deletion.CASCADE, related_name='formatos_funcion', to='cine.funcion')),
            ],
            options={
                'verbose_name': 'Formato de Función',
                'verbose_name_plural': 'Formatos de Función',
                'db_table': 'funcion_formato',
                'ordering': ['funcion', 'formato'],
                'unique_together': {('funcion', 'formato')},
            },
        ),
    ]
