# Generated by Django 5.2.6 on 2025-11-04 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0007_formato_remove_funcion_formato_proyeccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre comercial del establecimiento', max_length=200, verbose_name='Nombre del Cine')),
                ('logo', models.ImageField(blank=True, help_text='Logo o imagen corporativa (opcional)', null=True, upload_to='cine/logos/', verbose_name='Logo del Cine')),
                ('cuil_cuit', models.CharField(help_text='Formato: 20-12345678-9', max_length=13, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use: XX-XXXXXXXX-X', regex='^\\d{2}-\\d{8}-\\d{1}$')], verbose_name='CUIL/CUIT')),
                ('razon_social', models.CharField(help_text='Nombre legal de la empresa', max_length=200, verbose_name='Razón Social')),
                ('direccion', models.CharField(help_text='Dirección completa del cine', max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(help_text='Número de contacto principal', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(help_text='Correo electrónico para consultas', max_length=254, verbose_name='Email de Contacto')),
                ('horario_apertura', models.TimeField(help_text='Hora de apertura del cine', verbose_name='Horario de Apertura')),
                ('horario_cierre', models.TimeField(help_text='Hora de cierre del cine', verbose_name='Horario de Cierre')),
                ('facebook', models.URLField(blank=True, help_text='URL completa del perfil', null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, help_text='URL completa del perfil', null=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, help_text='URL completa del perfil', null=True, verbose_name='Twitter/X')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve del cine (para mostrar en el sitio)', null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Cine',
                'verbose_name_plural': 'Configuración del Cine',
                'db_table': 'configuracion_cine',
            },
        ),
    ]
