# Generated by Django 5.2.6 on 2025-11-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0008_configuracioncine'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncine',
            name='minutos_limpieza',
            field=models.PositiveIntegerField(default=30, help_text='Tiempo entre funciones para limpieza de sala (en minutos)', verbose_name='Minutos de Limpieza'),
        ),
    ]
