# Generated by Django 5.2.6 on 2025-11-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0009_configuracioncine_minutos_limpieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='clasificacion',
            field=models.CharField(choices=[('ATP', 'Apta para todo público'), ('+13', 'Mayores de 13 años'), ('+16', 'Mayores de 16 años'), ('+18', 'Mayores de 18 años')], default='ATP', help_text='Clasificación por edad de la película.', max_length=10),
        ),
    ]
