# Generated by Django 5.2.6 on 2025-11-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0010_pelicula_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='idioma',
            field=models.CharField(choices=[('DOBLADA', 'Doblada'), ('SUBTITULADA', 'Subtitulada'), ('NATIVA', 'Idioma Original')], default='DOBLADA', help_text='Idioma/audio de la función', max_length=20),
        ),
    ]
