# Generated by Django 5.2.6 on 2025-11-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0011_funcion_idioma'),
    ]

    operations = [
        migrations.AddField(
            model_name='formato',
            name='categoria',
            field=models.CharField(choices=[('VISUAL', 'Visual (2D/3D)'), ('EXPERIENCIA', 'Experiencia (4DX, D-BOX, 4D)'), ('PANTALLA', 'Pantalla (IMAX, ScreenX, Standard)'), ('AUDIO', 'Audio (Dolby Atmos, DTS, etc)'), ('OTRO', 'Otro')], default='VISUAL', help_text='Categoría del formato para facilitar filtrado', max_length=20),
        ),
    ]
