# Generated by Django 5.2.6 on 2025-11-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0012_formato_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='butaca',
            name='es_pasillo',
            field=models.BooleanField(default=False, help_text='Marca si esta posición es un pasillo (no seleccionable)'),
        ),
        migrations.AlterField(
            model_name='butaca',
            name='tipo',
            field=models.CharField(choices=[('GENERAL', 'General'), ('VIP', 'VIP'), ('DISCAPACITADO', 'Discapacitado'), ('4D', '4D'), ('PASILLO', 'Pasillo')], default='GENERAL', help_text='Tipo de butaca', max_length=20),
        ),
    ]
