# Generated by Django 5.2.6 on 2025-11-06 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0013_butaca_es_pasillo_alter_butaca_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='pelicula',
            field=models.ForeignKey(help_text='La película que se proyectará en esta función', on_delete=django.db.models.deletion.PROTECT, related_name='funciones', to='cine.pelicula'),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='sala',
            field=models.ForeignKey(help_text='La sala donde se proyectará la función', on_delete=django.db.models.deletion.PROTECT, related_name='funciones', to='cine.sala'),
        ),
    ]
