# Generated by Django 5.2.6 on 2025-11-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0014_alter_funcion_pelicula_alter_funcion_sala'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sala',
            table='sala',
        ),
    ]
