# Generated by Django 5.2.6 on 2025-11-12 21:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0015_alter_sala_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFuncion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(help_text='Fecha y hora de inicio de la función')),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base de la entrada para esta función (puede variar del precio de la sala)', max_digits=8)),
                ('idioma', models.CharField(choices=[('DOBLADA', 'Doblada'), ('SUBTITULADA', 'Subtitulada'), ('NATIVA', 'Idioma Original')], default='DOBLADA', help_text='Idioma/audio de la función', max_length=20)),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pelicula', models.ForeignKey(blank=True, db_constraint=False, help_text='La película que se proyectará en esta función', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cine.pelicula')),
                ('sala', models.ForeignKey(blank=True, db_constraint=False, help_text='La sala donde se proyectará la función', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cine.sala')),
            ],
            options={
                'verbose_name': 'historical Función',
                'verbose_name_plural': 'historical Funciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPelicula',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titulo', models.CharField(help_text='El título de la película.', max_length=200)),
                ('sinopsis', models.TextField(help_text='Una breve descripción de la trama.')),
                ('director', models.CharField(help_text='El director de la película.', max_length=100)),
                ('genero', models.CharField(choices=[('ACCION', 'Acción'), ('AVENTURA', 'Aventura'), ('COMEDIA', 'Comedia'), ('DRAMA', 'Drama'), ('CIENCIA_FICCION', 'Ciencia Ficción'), ('TERROR', 'Terror'), ('FANTASIA', 'Fantasía'), ('MUSICAL', 'Musical'), ('ANIMACION', 'Animación')], help_text='El género principal.', max_length=50)),
                ('duracion', models.PositiveIntegerField(help_text='La duración en minutos.')),
                ('fecha_estreno', models.DateField(help_text='La fecha de estreno en cines.')),
                ('clasificacion', models.CharField(choices=[('ATP', 'Apta para todo público'), ('+13', 'Mayores de 13 años'), ('+16', 'Mayores de 16 años'), ('+18', 'Mayores de 18 años')], default='ATP', help_text='Clasificación por edad de la película.', max_length=10)),
                ('imagen_portada', models.TextField(blank=True, help_text='La imagen de portada o póster de la película.', max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Película',
                'verbose_name_plural': 'historical Películas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSala',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(db_index=True, help_text='Número único de la sala (ej: 1, 2, 3...)')),
                ('nombre', models.CharField(help_text="Nombre descriptivo de la sala (ej: 'Sala Premium A')", max_length=100)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la sala está disponible para proyecciones')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la sala (equipamiento, mantenimiento, etc.)', null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Sala',
                'verbose_name_plural': 'historical Salas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
