# Generated by Django 5.2.6 on 2025-11-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0019_remove_old_genero_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpelicula',
            name='genero',
        ),
        migrations.AlterField(
            model_name='genero',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
