# Generated by Django 5.2.6 on 2025-11-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0020_remove_historicalpelicula_genero_alter_genero_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpelicula',
            name='acepta_promociones',
            field=models.BooleanField(default=True, help_text='Master switch: si es False, bloquea cualquier descuento.'),
        ),
        migrations.AddField(
            model_name='historicalpelicula',
            name='es_estreno',
            field=models.BooleanField(default=False, help_text='Indica si es un lanzamiento reciente.'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='acepta_promociones',
            field=models.BooleanField(default=True, help_text='Master switch: si es False, bloquea cualquier descuento.'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='es_estreno',
            field=models.BooleanField(default=False, help_text='Indica si es un lanzamiento reciente.'),
        ),
    ]
