# Generated by Django 5.2.6 on 2025-11-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0021_historicalpelicula_acepta_promociones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncine',
            name='reserva_tiempo_espera',
            field=models.PositiveIntegerField(default=10, help_text='Minutos que una butaca permanece reservada antes de liberarse automáticamente si no se completa el pago.', verbose_name='Tiempo de Reserva (min)'),
        ),
    ]
