# Generated by Django 5.2.6 on 2025-11-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0022_configuracioncine_reserva_tiempo_espera'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsala',
            name='capacidad_total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='sala',
            name='capacidad_total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
