# Generated by Django 5.2.6 on 2025-11-26 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0023_historicalsala_capacidad_total_sala_capacidad_total'),
        ('promociones', '0015_yield_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='estado_promocion',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('OFERTA_ACTIVA', 'Oferta Activa')], default='NORMAL', help_text='Estado de promoción automática para esta función', max_length=20),
        ),
        migrations.AddField(
            model_name='funcion',
            name='promocion_aplicada',
            field=models.ForeignKey(blank=True, help_text='Promoción automática actualmente vigente para esta función', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funciones_con_oferta', to='promociones.promocion'),
        ),
        migrations.AddField(
            model_name='historicalfuncion',
            name='estado_promocion',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('OFERTA_ACTIVA', 'Oferta Activa')], default='NORMAL', help_text='Estado de promoción automática para esta función', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalfuncion',
            name='promocion_aplicada',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Promoción automática actualmente vigente para esta función', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='promociones.promocion'),
        ),
    ]
