# Generated by Django 5.2.6 on 2025-12-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0024_yield_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butaca',
            name='tipo',
            field=models.CharField(choices=[('GENERAL', 'General'), ('DISCAPACITADO', 'Discapacitado'), ('4D', '4D'), ('PASILLO', 'Pasillo')], default='GENERAL', help_text='Tipo de butaca', max_length=20),
        ),
    ]
