# Generated by Django 5.2.6 on 2025-12-01 15:04

from django.db import migrations


def convert_vip_to_general(apps, schema_editor):
    """
    Convierte todas las butacas VIP existentes a tipo GENERAL
    """
    Butaca = apps.get_model('cine', 'Butaca')
    vip_butacas = Butaca.objects.filter(tipo='VIP')
    count = vip_butacas.count()
    
    if count > 0:
        vip_butacas.update(tipo='GENERAL')
        print(f"[OK] Convertidas {count} butacas VIP a GENERAL")
    else:
        print("[INFO] No se encontraron butacas VIP para convertir")


def reverse_conversion(apps, schema_editor):
    """
    Reversión: No hacemos nada porque no podemos saber cuáles eran VIP originalmente
    """
    print("[WARNING] Nota: No se puede revertir la conversion de VIP a GENERAL automaticamente")


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0025_remove_vip_tipo'),
    ]

    operations = [
        migrations.RunPython(convert_vip_to_general, reverse_conversion),
    ]
