# Generated by Django 5.2.6 on 2025-12-01 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0026_convert_vip_to_general'),
        ('promociones', '0017_alter_promocion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncine',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción breve del cine (para mostrar en el sitio)', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='configuracioncine',
            name='facebook',
            field=models.URLField(blank=True, default='', help_text='URL completa del perfil', verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='configuracioncine',
            name='instagram',
            field=models.URLField(blank=True, default='', help_text='URL completa del perfil', verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='configuracioncine',
            name='logo',
            field=models.ImageField(blank=True, default='', help_text='Logo o imagen corporativa (opcional)', upload_to='cine/logos/', verbose_name='Logo del Cine'),
        ),
        migrations.AlterField(
            model_name='configuracioncine',
            name='twitter',
            field=models.URLField(blank=True, default='', help_text='URL completa del perfil', verbose_name='Twitter/X'),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='promocion_aplicada',
            field=models.ForeignKey(blank=True, help_text='Promoción automática actualmente vigente para esta función (puede ser null)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funciones_con_oferta', to='promociones.promocion'),
        ),
        migrations.AlterField(
            model_name='historicalfuncion',
            name='promocion_aplicada',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Promoción automática actualmente vigente para esta función (puede ser null)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='promociones.promocion'),
        ),
        migrations.AlterField(
            model_name='historicalpelicula',
            name='imagen_portada',
            field=models.TextField(blank=True, default='', help_text='La imagen de portada o póster de la película.', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalsala',
            name='observaciones',
            field=models.TextField(blank=True, default='', help_text='Notas adicionales sobre la sala (equipamiento, mantenimiento, etc.)'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen_portada',
            field=models.ImageField(blank=True, default='', help_text='La imagen de portada o póster de la película.', upload_to='portadas_peliculas/'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='observaciones',
            field=models.TextField(blank=True, default='', help_text='Notas adicionales sobre la sala (equipamiento, mantenimiento, etc.)'),
        ),
    ]
