# Generated by Django 5.2.6 on 2025-12-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0027_alter_configuracioncine_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='butaca',
            new_name='IDX_butaca_sala_fila_numero',
            old_name='cine_butaca_sala_id_1c63a7_idx',
        ),
        migrations.RenameIndex(
            model_name='funcion',
            new_name='IDX_funcion_fecha_sala',
            old_name='funciones_fecha_h_ce0ee9_idx',
        ),
        migrations.RenameIndex(
            model_name='funcion',
            new_name='IDX_funcion_pelicula_fecha',
            old_name='funciones_pelicul_94f0ff_idx',
        ),
        migrations.AlterUniqueTogether(
            name='butaca',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='funcionformato',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='formato',
            name='nombre',
            field=models.CharField(help_text='Nombre del formato (ej: 2D, 3D, IMAX, 4DX)', max_length=50),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalsala',
            name='numero',
            field=models.PositiveIntegerField(help_text='Número único de la sala (ej: 1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='numero',
            field=models.PositiveIntegerField(help_text='Número único de la sala (ej: 1, 2, 3...)'),
        ),
        migrations.AddConstraint(
            model_name='butaca',
            constraint=models.UniqueConstraint(fields=('sala', 'fila', 'numero'), name='UQ_butaca_sala_fila_numero'),
        ),
        migrations.AddConstraint(
            model_name='formato',
            constraint=models.UniqueConstraint(fields=('nombre',), name='UQ_formato_nombre'),
        ),
        migrations.AddConstraint(
            model_name='funcionformato',
            constraint=models.UniqueConstraint(fields=('funcion', 'formato'), name='UQ_funcionformato_funcion_formato'),
        ),
        migrations.AddConstraint(
            model_name='genero',
            constraint=models.UniqueConstraint(fields=('nombre',), name='UQ_genero_nombre'),
        ),
        migrations.AddConstraint(
            model_name='sala',
            constraint=models.UniqueConstraint(fields=('numero',), name='UQ_sala_numero'),
        ),
    ]
