# Generated by Django 5.2.6 on 2025-12-01 20:03

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0028_rename_cine_butaca_sala_id_1c63a7_idx_idx_butaca_sala_fila_numero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalConfiguracionCine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre comercial del establecimiento', max_length=200, verbose_name='Nombre del Cine')),
                ('logo', models.TextField(blank=True, default='', help_text='Logo o imagen corporativa (opcional)', max_length=100, verbose_name='Logo del Cine')),
                ('cuil_cuit', models.CharField(help_text='Formato: 20-12345678-9', max_length=13, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use: XX-XXXXXXXX-X', regex='^\\d{2}-\\d{8}-\\d{1}$')], verbose_name='CUIL/CUIT')),
                ('razon_social', models.CharField(help_text='Nombre legal de la empresa', max_length=200, verbose_name='Razón Social')),
                ('direccion', models.CharField(help_text='Dirección completa del cine', max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(help_text='Número de contacto principal', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(help_text='Correo electrónico para consultas', max_length=254, verbose_name='Email de Contacto')),
                ('horario_apertura', models.TimeField(help_text='Hora de apertura del cine', verbose_name='Horario de Apertura')),
                ('horario_cierre', models.TimeField(help_text='Hora de cierre del cine', verbose_name='Horario de Cierre')),
                ('minutos_limpieza', models.PositiveIntegerField(default=30, help_text='Tiempo entre funciones para limpieza de sala (en minutos)', verbose_name='Minutos de Limpieza')),
                ('reserva_tiempo_espera', models.PositiveIntegerField(default=10, help_text='Minutos que una butaca permanece reservada antes de liberarse automáticamente si no se completa el pago.', verbose_name='Tiempo de Reserva (min)')),
                ('facebook', models.URLField(blank=True, default='', help_text='URL completa del perfil', verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, default='', help_text='URL completa del perfil', verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, default='', help_text='URL completa del perfil', verbose_name='Twitter/X')),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción breve del cine (para mostrar en el sitio)', verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Configuración del Cine',
                'verbose_name_plural': 'historical Configuración del Cine',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
