# Generated by Django 5.2.6 on 2025-12-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0029_historicalconfiguracioncine'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('PREVENTA', 'Preventa'), ('AGOTADA', 'Agotada')], default='ACTIVA', help_text='Estado actual de la función', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalfuncion',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('PREVENTA', 'Preventa'), ('AGOTADA', 'Agotada')], default='ACTIVA', help_text='Estado actual de la función', max_length=20),
        ),
    ]
