# Generated by Django 5.2.6 on 2025-12-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0030_funcion_estado_historicalfuncion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('PREVENTA', 'Preventa'), ('AGOTADA', 'Agotada'), ('INACTIVA', 'Inactiva')], default='ACTIVA', help_text='Estado actual de la función', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalfuncion',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('PREVENTA', 'Preventa'), ('AGOTADA', 'Agotada'), ('INACTIVA', 'Inactiva')], default='ACTIVA', help_text='Estado actual de la función', max_length=20),
        ),
    ]
