# Generated by Django 5.2.6 on 2026-02-08 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0031_alter_funcion_estado_alter_historicalfuncion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcion',
            name='promocion_aplicada',
        ),
        migrations.RemoveField(
            model_name='historicalfuncion',
            name='promocion_aplicada',
        ),
    ]
