# Generated by Django 5.2.6 on 2026-02-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0032_remove_funcion_promocion_aplicada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpelicula',
            name='anio_estreno',
            field=models.PositiveIntegerField(blank=True, default=2024, editable=False, help_text='Año de estreno calculado automáticamente desde fecha_estreno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='anio_estreno',
            field=models.PositiveIntegerField(blank=True, default=2024, editable=False, help_text='Año de estreno calculado automáticamente desde fecha_estreno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalpelicula',
            name='acepta_promociones',
            field=models.BooleanField(default=True, help_text='si lo presiona bloquea cualquier descuento.'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='acepta_promociones',
            field=models.BooleanField(default=True, help_text='si lo presiona bloquea cualquier descuento.'),
        ),
        migrations.AddConstraint(
            model_name='pelicula',
            constraint=models.UniqueConstraint(fields=('titulo', 'anio_estreno'), name='unique_pelicula_titulo_anio', violation_error_message='Ya existe una película con este título en el mismo año'),
        ),
    ]
