# Generated by Django 5.2.6 on 2026-02-11 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0033_historicalpelicula_anio_estreno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, help_text='Precio base de la entrada para esta función (puede variar del precio de la sala)', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='historicalfuncion',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, help_text='Precio base de la entrada para esta función (puede variar del precio de la sala)', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
