# Generated by manual creation on 2026-02-13
# Migration: Sistema de Horarios Flexibles por Día de la Semana

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


def migrar_horarios_antiguos(apps, schema_editor):
    """
    Migración de datos: Copia horario_apertura/cierre actuales
    a 7 registros de HorarioAtencion (uno por cada día de la semana).
    
    Estrategia: Replicar el horario único actual para TODOS los días,
    permitiendo luego al administrador personalizar por día según necesidad.
    """
    ConfiguracionCine = apps.get_model('cine', 'ConfiguracionCine')
    HorarioAtencion = apps.get_model('cine', 'HorarioAtencion')
    
    try:
        config = ConfiguracionCine.objects.get(pk=1)
    except ConfiguracionCine.DoesNotExist:
        # No hay configuración, salir sin hacer nada
        print("⚠️ No se encontró ConfiguracionCine, omitiendo migración de horarios.")
        return
    
    # Verificar que existan los campos antiguos antes de migrar
    if not hasattr(config, 'horario_apertura') or not hasattr(config, 'horario_cierre'):
        print("⚠️ Los campos horario_apertura/cierre no existen, omitiendo migración.")
        return
    
    # Si ya existen horarios, no hacer nada (idempotencia)
    if HorarioAtencion.objects.filter(configuracion_cine=config).exists():
        print("✅ Ya existen HorarioAtencion, omitiendo migración de datos.")
        return
    
    # Crear 7 registros (uno por cada día de la semana: 0=Lunes, 6=Domingo)
    dias_nombres = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']
    
    for dia in range(7):
        HorarioAtencion.objects.create(
            configuracion_cine=config,
            dia_semana=dia,
            hora_apertura=config.horario_apertura,  # Ej: 10:00
            hora_cierre=config.horario_cierre,      # Ej: 23:00
            activo=True,
            orden=0
        )
        print(f"✅ Creado horario para {dias_nombres[dia]}: "
              f"{config.horario_apertura} - {config.horario_cierre}")
    
    print(f"✅ Migración completada: {len(dias_nombres)} horarios creados.")


def reverse_migration(apps, schema_editor):
    """
    Rollback: Elimina todos los registros de HorarioAtencion.
    Nota: Los campos horario_apertura/cierre se restaurarán en el paso RemoveField.
    """
    HorarioAtencion = apps.get_model('cine', 'HorarioAtencion')
    count = HorarioAtencion.objects.all().count()
    HorarioAtencion.objects.all().delete()
    print(f"⏮️ Rollback: Eliminados {count} registros de HorarioAtencion.")


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0034_alter_funcion_precio_base_and_more'),
    ]

    operations = [
        # ========================================================================
        # PASO 1: Crear modelo HorarioAtencion
        # ========================================================================
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(
                    choices=[
                        (0, 'Lunes'),
                        (1, 'Martes'),
                        (2, 'Miércoles'),
                        (3, 'Jueves'),
                        (4, 'Viernes'),
                        (5, 'Sábado'),
                        (6, 'Domingo')
                    ],
                    help_text='0=Lunes, 6=Domingo',
                    verbose_name='Día de la Semana'
                )),
                ('hora_apertura', models.TimeField(
                    help_text='Hora de inicio del rango',
                    verbose_name='Hora de Apertura'
                )),
                ('hora_cierre', models.TimeField(
                    help_text='Hora de fin del rango',
                    verbose_name='Hora de Cierre'
                )),
                ('activo', models.BooleanField(
                    default=True,
                    help_text='Desmarcar para deshabilitar temporalmente este horario sin eliminarlo',
                    verbose_name='Activo'
                )),
                ('orden', models.PositiveSmallIntegerField(
                    default=0,
                    help_text='Orden de visualización para múltiples rangos del mismo día (0, 1, 2...)',
                    verbose_name='Orden'
                )),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('configuracion_cine', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='horarios_atencion',
                    to='cine.configuracioncine',
                    verbose_name='Configuración del Cine'
                )),
            ],
            options={
                'verbose_name': 'Horario de Atención',
                'verbose_name_plural': 'Horarios de Atención',
                'db_table': 'horarios_atencion',
                'ordering': ['dia_semana', 'orden', 'hora_apertura'],
            },
        ),
        
        # ========================================================================
        # PASO 2: Crear índices para optimizar consultas
        # ========================================================================
        migrations.AddIndex(
            model_name='horarioatencion',
            index=models.Index(
                fields=['dia_semana', 'activo'],
                name='idx_horario_dia_activo'
            ),
        ),
        migrations.AddIndex(
            model_name='horarioatencion',
            index=models.Index(
                fields=['configuracion_cine', 'dia_semana'],
                name='idx_horario_config_dia'
            ),
        ),
        
        # ========================================================================
        # PASO 3: Agregar constraint de validación a nivel DB
        # ========================================================================
        migrations.AddConstraint(
            model_name='horarioatencion',
            constraint=models.CheckConstraint(
                check=models.Q(hora_cierre__gt=models.F('hora_apertura')),
                name='check_hora_cierre_mayor_apertura'
            ),
        ),
        
        # ========================================================================
        # PASO 4: Crear tabla de historial (simple-history)
        # ========================================================================
        migrations.CreateModel(
            name='HistoricalHorarioAtencion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(
                    choices=[
                        (0, 'Lunes'),
                        (1, 'Martes'),
                        (2, 'Miércoles'),
                        (3, 'Jueves'),
                        (4, 'Viernes'),
                        (5, 'Sábado'),
                        (6, 'Domingo')
                    ],
                    help_text='0=Lunes, 6=Domingo',
                    verbose_name='Día de la Semana'
                )),
                ('hora_apertura', models.TimeField(
                    help_text='Hora de inicio del rango',
                    verbose_name='Hora de Apertura'
                )),
                ('hora_cierre', models.TimeField(
                    help_text='Hora de fin del rango',
                    verbose_name='Hora de Cierre'
                )),
                ('activo', models.BooleanField(
                    default=True,
                    help_text='Desmarcar para deshabilitar temporalmente este horario sin eliminarlo',
                    verbose_name='Activo'
                )),
                ('orden', models.PositiveSmallIntegerField(
                    default=0,
                    help_text='Orden de visualización para múltiples rangos del mismo día (0, 1, 2...)',
                    verbose_name='Orden'
                )),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(
                    choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
                    max_length=1
                )),
                ('configuracion_cine', models.ForeignKey(
                    blank=True,
                    db_constraint=False,
                    null=True,
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='+',
                    to='cine.configuracioncine',
                    verbose_name='Configuración del Cine'
                )),
                ('history_user', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='+',
                    to='accounts.usuario' # Ajusta esto según tu modelo de usuario
                )),
            ],
            options={
                'verbose_name': 'historical Horario de Atención',
                'verbose_name_plural': 'historical Horarios de Atención',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        
        # ========================================================================
        # PASO 5: MIGRACIÓN DE DATOS (crítico)
        # ========================================================================
        migrations.RunPython(
            code=migrar_horarios_antiguos,
            reverse_code=reverse_migration
        ),
        
        # ========================================================================
        # PASO 6: Eliminar campos antiguos de ConfiguracionCine
        # ========================================================================
        # ADVERTENCIA: Este paso elimina los campos horario_apertura y horario_cierre.
        # Asegúrate de que la migración de datos fue exitosa antes de ejecutar esto.
        
        migrations.RemoveField(
            model_name='configuracioncine',
            name='horario_apertura',
        ),
        
        migrations.RemoveField(
            model_name='configuracioncine',
            name='horario_cierre',
        ),
        
        # También eliminar de HistoricalConfiguracionCine si existe
        migrations.RemoveField(
            model_name='historicalconfiguracioncine',
            name='horario_apertura',
        ),
        
        migrations.RemoveField(
            model_name='historicalconfiguracioncine',
            name='horario_cierre',
        ),
    ]
