# Generated by Django 5.2.6 on 2026-02-14 16:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0035_add_horarios_atencion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalExcepcionHorario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha específica de la excepción (ej: 25/12/2024)', verbose_name='Fecha')),
                ('cerrado', models.BooleanField(default=False, help_text='Marcar si el cine está completamente cerrado este día', verbose_name='Cine Cerrado')),
                ('hora_apertura', models.TimeField(blank=True, help_text='Hora de apertura (solo si cerrado=False)', null=True, verbose_name='Hora de Apertura')),
                ('hora_cierre', models.TimeField(blank=True, help_text='Hora de cierre (solo si cerrado=False)', null=True, verbose_name='Hora de Cierre')),
                ('descripcion', models.CharField(blank=True, default='', help_text='Motivo de la excepción (ej: "Navidad", "Mantenimiento")', max_length=200, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('configuracion_cine', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cine.configuracioncine', verbose_name='Configuración del Cine')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Excepción de Horario',
                'verbose_name_plural': 'historical Excepciones de Horarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ExcepcionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha específica de la excepción (ej: 25/12/2024)', verbose_name='Fecha')),
                ('cerrado', models.BooleanField(default=False, help_text='Marcar si el cine está completamente cerrado este día', verbose_name='Cine Cerrado')),
                ('hora_apertura', models.TimeField(blank=True, help_text='Hora de apertura (solo si cerrado=False)', null=True, verbose_name='Hora de Apertura')),
                ('hora_cierre', models.TimeField(blank=True, help_text='Hora de cierre (solo si cerrado=False)', null=True, verbose_name='Hora de Cierre')),
                ('descripcion', models.CharField(blank=True, default='', help_text='Motivo de la excepción (ej: "Navidad", "Mantenimiento")', max_length=200, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('configuracion_cine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones_horarios', to='cine.configuracioncine', verbose_name='Configuración del Cine')),
            ],
            options={
                'verbose_name': 'Excepción de Horario',
                'verbose_name_plural': 'Excepciones de Horarios',
                'db_table': 'excepciones_horarios',
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['configuracion_cine', 'fecha'], name='idx_excepcion_config_fecha'), models.Index(fields=['fecha', 'cerrado'], name='idx_excepcion_fecha_cerrado')],
                'constraints': [models.UniqueConstraint(fields=('configuracion_cine', 'fecha'), name='unique_excepcion_por_fecha')],
            },
        ),
    ]
