# Generated by Django 5.2.6 on 2026-02-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0036_excepcion_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='excepcionhorario',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Si se especifica, la excepción aplica desde "fecha" hasta "fecha_fin" (rango inclusivo)', null=True, verbose_name='Fecha de Fin (Opcional)'),
        ),
        migrations.AddField(
            model_name='historicalexcepcionhorario',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Si se especifica, la excepción aplica desde "fecha" hasta "fecha_fin" (rango inclusivo)', null=True, verbose_name='Fecha de Fin (Opcional)'),
        ),
        migrations.AlterField(
            model_name='excepcionhorario',
            name='fecha',
            field=models.DateField(help_text='Fecha de inicio de la excepción (ej: 25/12/2024). Si no se especifica fecha_fin, aplica solo a este día.', verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='historicalexcepcionhorario',
            name='fecha',
            field=models.DateField(help_text='Fecha de inicio de la excepción (ej: 25/12/2024). Si no se especifica fecha_fin, aplica solo a este día.', verbose_name='Fecha de Inicio'),
        ),
    ]
