# Generated by Django 5.2.6 on 2026-02-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0037_agregar_fecha_fin_excepcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsala',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='activa',
        ),
        migrations.AddField(
            model_name='funcion',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o fue dado de baja lógicamente', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='funcion',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue dado de baja', null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AddField(
            model_name='genero',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o fue dado de baja lógicamente', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='genero',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue dado de baja', null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AddField(
            model_name='historicalfuncion',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o fue dado de baja lógicamente', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='historicalfuncion',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue dado de baja', null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AddField(
            model_name='historicalpelicula',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o fue dado de baja lógicamente', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='historicalpelicula',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue dado de baja', null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AddField(
            model_name='historicalsala',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o fue dado de baja lógicamente', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='historicalsala',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue dado de baja', null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o fue dado de baja lógicamente', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue dado de baja', null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AddField(
            model_name='sala',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o fue dado de baja lógicamente', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='sala',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue dado de baja', null=True, verbose_name='Fecha de Baja'),
        ),
    ]
