# Generated by Django 5.2.6 on 2026-03-04 02:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0038_add_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncine',
            name='logo_local',
            field=models.ImageField(blank=True, help_text='Copia local optimizada del logo (respaldo sin internet)', null=True, upload_to='cine/logos/', verbose_name='Logo Local'),
        ),
        migrations.AddField(
            model_name='configuracioncine',
            name='logo_red',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Logo almacenado en Cloudinary (requiere conexión a internet)', max_length=255, null=True, verbose_name='Logo en Cloudinary'),
        ),
        migrations.AddField(
            model_name='historicalconfiguracioncine',
            name='logo_local',
            field=models.TextField(blank=True, help_text='Copia local optimizada del logo (respaldo sin internet)', max_length=100, null=True, verbose_name='Logo Local'),
        ),
        migrations.AddField(
            model_name='historicalconfiguracioncine',
            name='logo_red',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Logo almacenado en Cloudinary (requiere conexión a internet)', max_length=255, null=True, verbose_name='Logo en Cloudinary'),
        ),
        migrations.AddField(
            model_name='historicalpelicula',
            name='imagen_local',
            field=models.TextField(blank=True, help_text='Copia local optimizada de la imagen (respaldo sin internet)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalpelicula',
            name='imagen_red',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen almacenada en Cloudinary (requiere conexión a internet)', max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='imagen_local',
            field=models.ImageField(blank=True, help_text='Copia local optimizada de la imagen (respaldo sin internet)', null=True, upload_to='portadas_peliculas/'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='imagen_red',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen almacenada en Cloudinary (requiere conexión a internet)', max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='configuracioncine',
            name='logo',
            field=models.ImageField(blank=True, default='', help_text='[DEPRECADO] Usar logo_red/logo_local + get_logo_url', upload_to='cine/logos/', verbose_name='Logo del Cine'),
        ),
        migrations.AlterField(
            model_name='historicalconfiguracioncine',
            name='logo',
            field=models.TextField(blank=True, default='', help_text='[DEPRECADO] Usar logo_red/logo_local + get_logo_url', max_length=100, verbose_name='Logo del Cine'),
        ),
        migrations.AlterField(
            model_name='historicalpelicula',
            name='imagen_portada',
            field=models.TextField(blank=True, default='', help_text='[DEPRECADO] Usar imagen_red/imagen_local + get_poster_url', max_length=100),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen_portada',
            field=models.ImageField(blank=True, default='', help_text='[DEPRECADO] Usar imagen_red/imagen_local + get_poster_url', upload_to='portadas_peliculas/'),
        ),
    ]
