# Generated by Django 5.2.6 on 2026-03-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0040_funcion_fecha_activacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpelicula',
            name='youtube_trailer_key',
            field=models.CharField(blank=True, help_text="ID del video de YouTube del trailer oficial (ej: 'dQw4w9WgXcQ')", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='youtube_trailer_key',
            field=models.CharField(blank=True, help_text="ID del video de YouTube del trailer oficial (ej: 'dQw4w9WgXcQ')", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpelicula',
            name='acepta_promociones',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalpelicula',
            name='es_estreno',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='acepta_promociones',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='es_estreno',
            field=models.BooleanField(default=False),
        ),
    ]
