# Generated by Django 5.2.6 on 2026-03-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0041_historicalpelicula_youtube_trailer_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o fue dado de baja lógicamente', verbose_name='Activo')),
                ('fecha_baja', models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue dado de baja', null=True, verbose_name='Fecha de Baja')),
                ('nombre', models.CharField(help_text='Código de la clasificación (ej: ATP, +13, +16, +18)', max_length=10, unique=True)),
                ('descripcion', models.CharField(help_text='Descripción completa de la clasificación', max_length=200)),
                ('edad_minima', models.PositiveIntegerField(default=0, help_text='Edad mínima recomendada (0 para ATP)')),
                ('orden', models.PositiveIntegerField(default=100, help_text='Orden de visualización (menor número = mayor prioridad)')),
            ],
            options={
                'verbose_name': 'Clasificación de Edad',
                'verbose_name_plural': 'Clasificaciones de Edad',
                'db_table': 'cine_clasificacion',
                'ordering': ['orden', 'edad_minima', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('nombre',), name='UQ_clasificacion_nombre')],
            },
        ),
    ]
