# Generated by Django on 2026-03-06

from django.db import migrations


def crear_clasificaciones(apps, schema_editor):
    """Poblar la tabla de Clasificaciones con los valores estándar"""
    Clasificacion = apps.get_model('cine', 'Clasificacion')
    
    clasificaciones = [
        {
            'nombre': 'ATP',
            'descripcion': 'Apta para todo público',
            'edad_minima': 0
        },
        {
            'nombre': '+13',
            'descripcion': 'Mayores de 13 años',
            'edad_minima': 13
        },
        {
            'nombre': '+16',
            'descripcion': 'Mayores de 16 años',
            'edad_minima': 16
        },
        {
            'nombre': '+18',
            'descripcion': 'Mayores de 18 años',
            'edad_minima': 18
        },
    ]
    
    for datos in clasificaciones:
        Clasificacion.objects.get_or_create(
            nombre=datos['nombre'],
            defaults={
                'descripcion': datos['descripcion'],
                'edad_minima': datos['edad_minima']
            }
        )


def borrar_clasificaciones(apps, schema_editor):
    """Reverso: eliminar las clasificaciones creadas"""
    Clasificacion = apps.get_model('cine', 'Clasificacion')
    Clasificacion.objects.filter(nombre__in=['ATP', '+13', '+16', '+18']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0042_create_clasificacion_model'),
    ]

    operations = [
        migrations.RunPython(crear_clasificaciones, borrar_clasificaciones),
    ]
