# Generated by Django 5.2.6 on 2026-03-06 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0043_populate_clasificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpelicula',
            name='clasificacion_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Clasificación por edad (nuevo sistema)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cine.clasificacion'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='clasificacion_fk',
            field=models.ForeignKey(blank=True, help_text='Clasificación por edad (nuevo sistema)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='peliculas_temp', to='cine.clasificacion'),
        ),
    ]
