# Generated by Django on 2026-03-06

from django.db import migrations


def migrar_clasificaciones_a_fk(apps, schema_editor):
    """Migrar los datos del campo clasificacion (CharField) a clasificacion_fk (ForeignKey)"""
    Pelicula = apps.get_model('cine', 'Pelicula')
    Clasificacion = apps.get_model('cine', 'Clasificacion')
    
    # Mapeo de códigos a objetos Clasificacion
    clasificaciones_map = {}
    for clasificacion_obj in Clasificacion.objects.all():
        clasificaciones_map[clasificacion_obj.nombre] = clasificacion_obj
    
    # Migrar todas las películas
    peliculas_actualizadas = 0
    for pelicula in Pelicula.objects.all():
        codigo_clasificacion = pelicula.clasificacion
        
        if codigo_clasificacion in clasificaciones_map:
            pelicula.clasificacion_fk = clasificaciones_map[codigo_clasificacion]
            pelicula.save(update_fields=['clasificacion_fk'])
            peliculas_actualizadas += 1
        else:
            # Si no existe la clasificación, usar ATP por defecto
            atp = clasificaciones_map.get('ATP')
            if atp:
                pelicula.clasificacion_fk = atp
                pelicula.save(update_fields=['clasificacion_fk'])
                peliculas_actualizadas += 1
    
    print(f"✅ Migradas {peliculas_actualizadas} películas a nuevo sistema de clasificaciones")


def reverso_migrar_clasificaciones(apps, schema_editor):
    """Reverso: limpiar el campo clasificacion_fk"""
    Pelicula = apps.get_model('cine', 'Pelicula')
    Pelicula.objects.all().update(clasificacion_fk=None)


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0044_add_clasificacion_fk_field'),
    ]

    operations = [
        migrations.RunPython(migrar_clasificaciones_a_fk, reverso_migrar_clasificaciones),
    ]
