# Generated by Django 5.2.6 on 2026-03-07 00:00

import django.db.models.deletion
from django.db import migrations, models


def _split_director_name(raw_name):
    nombre_limpio = ' '.join((raw_name or '').strip().split())
    if not nombre_limpio:
        return 'Desconocido', ''

    if ',' in nombre_limpio:
        apellido_raw, nombre_raw = [x.strip() for x in nombre_limpio.split(',', 1)]
        nombre = (nombre_raw or nombre_limpio).title()
        apellido = apellido_raw.title()
        return nombre, apellido

    partes = nombre_limpio.split()
    if len(partes) == 1:
        return partes[0].title(), ''

    nombre = ' '.join(partes[:-1]).title()
    apellido = partes[-1].title()
    return nombre, apellido


def _full_name(nombre, apellido):
    return f"{(nombre or '').strip()} {(apellido or '').strip()}".strip() or 'Desconocido'


def migrate_director_text_to_fk(apps, schema_editor):
    Director = apps.get_model('cine', 'Director')
    Pelicula = apps.get_model('cine', 'Pelicula')
    HistoricalPelicula = apps.get_model('cine', 'HistoricalPelicula')

    cache = {}

    def resolve_director(raw_name):
        normalized_key = ' '.join((raw_name or '').strip().split()).casefold()
        if not normalized_key:
            normalized_key = 'desconocido'

        director_obj = cache.get(normalized_key)
        if director_obj:
            return director_obj

        nombre, apellido = _split_director_name(raw_name)
        director_obj, _ = Director.objects.get_or_create(nombre=nombre, apellido=apellido)
        cache[normalized_key] = director_obj
        return director_obj

    peliculas_a_actualizar = []
    for pelicula in Pelicula.objects.all().only('id', 'director'):
        director_obj = resolve_director(getattr(pelicula, 'director', ''))
        pelicula.director_fk_id = director_obj.id
        peliculas_a_actualizar.append(pelicula)

    if peliculas_a_actualizar:
        Pelicula.objects.bulk_update(peliculas_a_actualizar, ['director_fk'])

    historicas_a_actualizar = []
    for hp in HistoricalPelicula.objects.all().only('history_id', 'director'):
        director_obj = resolve_director(getattr(hp, 'director', ''))
        hp.director_fk_id = director_obj.id
        historicas_a_actualizar.append(hp)

    if historicas_a_actualizar:
        HistoricalPelicula.objects.bulk_update(historicas_a_actualizar, ['director_fk'])


def rollback_director_fk_to_text(apps, schema_editor):
    Director = apps.get_model('cine', 'Director')
    Pelicula = apps.get_model('cine', 'Pelicula')
    HistoricalPelicula = apps.get_model('cine', 'HistoricalPelicula')

    director_map = {
        row['id']: _full_name(row['nombre'], row['apellido'])
        for row in Director.objects.values('id', 'nombre', 'apellido')
    }

    peliculas_a_actualizar = []
    for pelicula in Pelicula.objects.all().only('id', 'director_fk_id'):
        pelicula.director = director_map.get(pelicula.director_fk_id, 'Desconocido')
        peliculas_a_actualizar.append(pelicula)

    if peliculas_a_actualizar:
        Pelicula.objects.bulk_update(peliculas_a_actualizar, ['director'])

    historicas_a_actualizar = []
    for hp in HistoricalPelicula.objects.all().only('history_id', 'director_fk_id'):
        hp.director = director_map.get(hp.director_fk_id, 'Desconocido')
        historicas_a_actualizar.append(hp)

    if historicas_a_actualizar:
        HistoricalPelicula.objects.bulk_update(historicas_a_actualizar, ['director'])


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0047_remove_clasificacion_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True, default='')),
                ('tmdb_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
                'ordering': ['apellido', 'nombre'],
                'db_table': 'directores',
            },
        ),
        migrations.AddField(
            model_name='historicalpelicula',
            name='director_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cine.director'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='director_fk',
            field=models.ForeignKey(blank=True, help_text='Director principal de la pelicula.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='peliculas', to='cine.director'),
        ),
        migrations.RunPython(migrate_director_text_to_fk, rollback_director_fk_to_text),
        migrations.RemoveField(
            model_name='historicalpelicula',
            name='director',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='director',
        ),
        migrations.RenameField(
            model_name='historicalpelicula',
            old_name='director_fk',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='director_fk',
            new_name='director',
        ),
        migrations.AlterField(
            model_name='historicalpelicula',
            name='director',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cine.director'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.ForeignKey(help_text='Director principal de la pelicula.', on_delete=django.db.models.deletion.PROTECT, related_name='peliculas', to='cine.director'),
        ),
    ]
