# Generated by Django 5.2.6 on 2026-03-11 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0049_fix_bunker_pelicula_integridad_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificacion',
            options={'ordering': ['edad_minima', 'nombre'], 'verbose_name': 'Clasificación de Edad', 'verbose_name_plural': 'Clasificaciones de Edad'},
        ),
        migrations.AddField(
            model_name='butaca',
            name='en_mantenimiento',
            field=models.BooleanField(default=False, help_text='Indica que la butaca está fuera de servicio temporalmente y no puede ser vendida ni seleccionada.', verbose_name='En mantenimiento'),
        ),
        migrations.AddField(
            model_name='configuracioncine',
            name='fecha_inicio_actividad',
            field=models.DateField(blank=True, help_text='Fecha en que el cine comenzó sus actividades (para comprobantes fiscales)', null=True, verbose_name='Fecha de Inicio de Actividad'),
        ),
        migrations.AddField(
            model_name='historicalconfiguracioncine',
            name='fecha_inicio_actividad',
            field=models.DateField(blank=True, help_text='Fecha en que el cine comenzó sus actividades (para comprobantes fiscales)', null=True, verbose_name='Fecha de Inicio de Actividad'),
        ),
        migrations.AlterField(
            model_name='historicalpelicula',
            name='clasificacion',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Clasificación por edad de la película', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cine.clasificacion'),
        ),
        migrations.AlterField(
            model_name='historicalpelicula',
            name='director',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Director principal de la pelicula.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cine.director'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='clasificacion',
            field=models.ForeignKey(help_text='Clasificación por edad de la película', on_delete=django.db.models.deletion.PROTECT, related_name='peliculas', to='cine.clasificacion'),
        ),
    ]
