# Generated by Django 5.2.6 on 2026-03-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0050_alter_clasificacion_options_butaca_en_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncine',
            name='fecha_inicio_actividad',
            field=models.DateField(blank=True, help_text='Fecha en que el cine comenzó sus actividades (para comprobantes)', null=True, verbose_name='Fecha de Inicio de Actividad'),
        ),
        migrations.AlterField(
            model_name='historicalconfiguracioncine',
            name='fecha_inicio_actividad',
            field=models.DateField(blank=True, help_text='Fecha en que el cine comenzó sus actividades (para comprobantes)', null=True, verbose_name='Fecha de Inicio de Actividad'),
        ),
    ]
