# Generated by Django 5.2.6 on 2026-03-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0051_entrada_unique_constraint_condicional'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='director',
            constraint=models.UniqueConstraint(condition=models.Q(('tmdb_id__isnull', True)), fields=('nombre', 'apellido'), name='unique_director_nombre_apellido_sin_tmdb'),
        ),
    ]
