# Generated by Django 5.2.6 on 2026-03-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0052_director_unique_nombre_apellido_sin_tmdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o fue dado de baja lógicamente', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='director',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue dado de baja', null=True, verbose_name='Fecha de Baja'),
        ),
    ]
