# Generated by Django 5.2.6 on 2026-03-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0051_update_bunker_pelicula_integridad_allow_numeric_title'),
        ('cine', '0053_director_activo_director_fecha_baja'),
    ]

    operations = [
    ]
