# Generated by Django 5.2.6 on 2025-11-30 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_remove_cliente_direccion_cliente_acepta_marketing'),
        ('cine', '0024_yield_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='accounts.cliente')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='cine.funcion')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='cine.pelicula')),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'db_table': 'valoraciones',
                'constraints': [models.UniqueConstraint(fields=('cliente', 'funcion'), name='unique_cliente_funcion_valoracion')],
            },
        ),
    ]
