# Generated by Django 5.2.6 on 2026-02-27 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_historicalusuario_email_alter_usuario_email'),
        ('cine', '0037_agregar_fecha_fin_excepcion'),
        ('valoraciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionValoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('url_destino', models.CharField(blank=True, max_length=500, null=True)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_valoracion', to='accounts.cliente')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='cine.funcion')),
            ],
            options={
                'verbose_name': 'Notificación de Valoración',
                'verbose_name_plural': 'Notificaciones de Valoración',
                'db_table': 'notificaciones_valoracion',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'funcion'), name='unique_cliente_funcion_notificacion')],
            },
        ),
    ]
